### PR TITLE
0.7.0 Release Prep

### PR DESCRIPTION
**Pull request by pbauman**
Updated CHANGES, added @nicholasmalaya to AUTHORS (thanks!), fixed one test that didn't run with `mpiexec -np 8` (or any -np except 1), distcheck fixes, updated so we don't distribute the license tool (that way it's only used in a repo clone, not a tarball), and updated LICENSE date to 2016.

### CODE REVIEW

**Comment by pbauman** [comment]
Barring any comments, will merge this COB tomorrow and do the release.

**Comment by pbauman** [comment]
@roystgnr says he's getting a compilation failure, but I can't reproduce with GCC 4.8.5, GCC 4.9.3, or GCC 5.3. Going to hold off on tagging this until we can sort that out.

**Comment by roystgnr** [comment]
Working on a fix in https://github.com/roystgnr/grins/tree/fix_metaprogramming - I'll try to have it done late tonight.

**Comment by pbauman** [comment]
Rebased on #411.

Going to clean up some new warnings that showed up with GCC 6.1 and then I think this should be good.

**Comment by roystgnr** [comment]
After the fix, Everything passes for me with -np 1.  With -np 4, GRINS master, I get

```
FAIL: exact_soln/poisson_periodic_2d_x.sh
FAIL: exact_soln/poisson_periodic_2d_y.sh
FAIL: exact_soln/poisson_periodic_3d_xz.sh
FAIL: exact_soln/poisson_periodic_3d_yz.sh
FAIL: exact_soln/poisson_periodic_3d_xy.sh
FAIL: regression/penalty_poiseuille_stab.sh
```

Linear solvers are failing to converge after 2500 steps and leading to nonlinear solver convergence failure too.

In the former cases it looks like I'm getting segfaults.  I'll see if I can hunt down where.

**Comment by pbauman** [comment]
Crap, thanks for pointing these out. I'll take care of the "after the fix" cases.

**Comment by pbauman** [comment]
OK, the `test/run_tests_parallel_loop.sh` script is almost through `-np 12` and here's what I've got:

<pre>
[12:36:25][pbauman@fry:/fry1/data/users/pbauman/research/grins/build/0.7.0-prep/devel/test]$ grep -e LIBMESH_RUN -e FAIL parallel_loop_check_tests.log | grep -v XFAIL
LIBMESH_RUN is mpiexec -np 1
# FAIL:  0
LIBMESH_RUN is mpiexec -np 2
# FAIL:  0
LIBMESH_RUN is mpiexec -np 3
LIBMESH_RUN is mpiexec -np 1
# FAIL:  0
LIBMESH_RUN is mpiexec -np 2
# FAIL:  0
LIBMESH_RUN is mpiexec -np 3
# FAIL:  0
LIBMESH_RUN is mpiexec -np 4
FAIL: regression/penalty_poiseuille_stab.sh
# FAIL:  1
LIBMESH_RUN is mpiexec -np 5
FAIL: regression/reacting_low_mach_antioch_kinetics_theory.sh
# FAIL:  1
LIBMESH_RUN is mpiexec -np 6
# FAIL:  0
LIBMESH_RUN is mpiexec -np 7
# FAIL:  0
LIBMESH_RUN is mpiexec -np 8
# FAIL:  0
LIBMESH_RUN is mpiexec -np 9
# FAIL:  0
LIBMESH_RUN is mpiexec -np 10
# FAIL:  0
LIBMESH_RUN is mpiexec -np 11
# FAIL:  0
LIBMESH_RUN is mpiexec -np 12
</pre>

I don't know how regressions got in for those two cases. I'll fix them. I'm not seeing the Poisson-periodic failures. I'm running with `SerialMesh` - were your failures with `ParallelMesh` @roystgnr?

**Comment by roystgnr** [comment]
They are indeed with ParallelMesh.  So if you'll worry about the solvers I'll worry about the segfaults.

**Comment by pbauman** [comment]
> They are indeed with ParallelMesh. So if you'll worry about the solvers I'll worry about the segfaults.

:+1:

**Comment by pbauman** [comment]
Just for completeness, here's the final result of `./run_tests_parallel_loop.sh 16`

<pre>
LIBMESH_RUN is mpiexec -np 1
# FAIL:  0
LIBMESH_RUN is mpiexec -np 2
# FAIL:  0
LIBMESH_RUN is mpiexec -np 3
LIBMESH_RUN is mpiexec -np 1
# FAIL:  0
LIBMESH_RUN is mpiexec -np 2
# FAIL:  0
LIBMESH_RUN is mpiexec -np 3
# FAIL:  0
LIBMESH_RUN is mpiexec -np 4
FAIL: regression/penalty_poiseuille_stab.sh
# FAIL:  1
LIBMESH_RUN is mpiexec -np 5
FAIL: regression/reacting_low_mach_antioch_kinetics_theory.sh
# FAIL:  1
LIBMESH_RUN is mpiexec -np 6
# FAIL:  0
LIBMESH_RUN is mpiexec -np 7
# FAIL:  0
LIBMESH_RUN is mpiexec -np 8
# FAIL:  0
LIBMESH_RUN is mpiexec -np 9
# FAIL:  0
LIBMESH_RUN is mpiexec -np 10
# FAIL:  0
LIBMESH_RUN is mpiexec -np 11
# FAIL:  0
LIBMESH_RUN is mpiexec -np 12
FAIL: regression/reacting_low_mach_antioch_kinetics_theory.sh
# FAIL:  1
LIBMESH_RUN is mpiexec -np 13
# FAIL:  0
LIBMESH_RUN is mpiexec -np 14
# FAIL:  0
LIBMESH_RUN is mpiexec -np 15
# FAIL:  0
LIBMESH_RUN is mpiexec -np 16
FAIL: regression/reacting_low_mach_antioch_statmech_constant_prandtl.sh
# FAIL:  1
</pre>

Going to focus first on PETSc versions to see if that's the issue.

**Comment by pbauman** [comment]
Good lord. I'm focusing on `regression/penalty_poiseuille_stab.sh` and going back to the revision *that we both ran successfully* now fails with `mpiexec -np 4`. I trolled through the issues and couldn't find what PETSc version we were using so I'll run through various PETSc versions to see if I can get success out of that commit again.

**Comment by roystgnr** [comment]
So the other regressions are clearly a libMesh failure, and not an easy one to fix.  Don't let them hold up 0.7.0.  If you want to hard-code mesh type == serial into the periodic BC tests that might be a good stopgap.

**Comment by pbauman** [comment]
> So the other regressions are clearly a libMesh failure, and not an easy one to fix. Don't let them hold up 0.7.0. If you want to hard-code mesh type == serial into the periodic BC tests that might be a good stopgap.

Glad I added the tests those tests then! I'll hardcode the test as you suggest and I'll add a check in the periodic boundary condition factory that throws an error that references the libMesh issue (that we can remove once it's sorted).

Then, once I sort out these other solver-related regressions, I'll update this ticket.

**Comment by pbauman** [comment]
Update: So I thought our original test updating was with switch from PETSC 3.5.x to PETSC 3.6.y, but apparently not for `regression/penalty_poiseuille_stab.sh`. Going back d4a432e (which is after the "robustness tweaks" and before shuffling I did down stream (that shouldn't have affected the convergence behavior of the test)) I get pass with `mpiexec -np 4` with PETSc 3.5.4 and fail with PETSc 3.6.0, all other things unchanged.

I'll work on updating options for this test and see if the other failures behave similarly.

**Comment by pbauman** [comment]
Update: Going back to the tip of this branch (pbauman/0.7.0-prep) and using PETSc 3.5.4, all the previous failing processor/test combinations pass.

**Comment by pbauman** [comment]
OK, in theory, we should be good again. I've run this through PETSc 3.5.4, 3.6.4, and 3.7.1 using GCC 4.8.5 and GCC 6.1.0 using the . I had to adjust a few a long the way. I'm resisting the urge to go back and change all the tests that use (implicitly or explicitly) `-sub_pc_type ilu` to `-sub_pc_type lu`. If this becomes a problem again, I'll probably do that to try and get more stability out of the tests again compiler/petsc changes. I did go ahead and update the parallel loop test script to take the TESTS="..." argument in 59c1876.

Two things left to do: tidy up some warnings when antioch and cantera are off and "serialize" the periodic tests/throw error for ParallelMesh in PeriodBoundary conditions.

**Comment by pbauman** [comment]
OK, I think we're ready to go. I snuck in adding accessors for the Neumann bcs that I'd forgotten to put in the boundary conditions PR.

We're almost to the point where we could add `-Werror` for Antioch enabled and Cantera disabled. Just a couple of warnings to clear up in `ParsedFunction` and `ParsedFEMFunction` on the libMesh side.

**Comment by roystgnr** [comment]
:trophy:

**Comment by pbauman** [comment]
Have to run now, but will merge, tag, and release tonight.

**Comment by pbauman** [comment]
(not merging now in case anyone wants to look a little closer before tonight)

**Pull request merged**
