### PR TITLE
Fix specialization-after-instantiation errors.

### LINKED ISSUE #510: GRINS master doesn't build for me with clang 3.9.0
I googled this error a bit but don't know exactly how to fix it yet... Do you guys ever build with clang?

```
boundary_conditions/src/catalycity_factory_abstract.C:41:52: error: explicit specialization of '_input' after instantiation
  const GetPot* FactoryWithGetPot<CatalycityBase>::_input = NULL;
                                                   ^
../src/boundary_conditions/include/grins/catalycity_factory_abstract.h:69:82: note: implicit instantiation first required here
    libMesh::UniquePtr<CatalycityBase> new_catalycity = this->build_catalycity( *_input, _section );
                                                                                 ^
```

### PR DESCRIPTION
**Pull request by jwpeterson**
This gets GRINS compiling for me with clang, thanks @roystgnr for compiler diagnostic interpretation.

Fixes #510.

### CODE REVIEW

**Comment by jwpeterson** [comment]
@brianmoose it looks like CIVET is not planning to test this PR, possibly because I overloaded it by doing 3 PRs at once?

**Comment by pbauman** [comment]
Weird. `femputer` doesn't even see this PR. No idea what happened. The server is up and is doing the merge-to-master runs on the 2 PRs I just merged.

**Comment by pbauman** [comment]
Also:

1. I need to get around to using clang more. I've avoided it because it's such a PITA to get libcxx built and used alongside it; our IT folks still have not moved away from CentOS 6, so the system libstdc++ is ancient

2. I owe you a beer for these fixes (regardless of whether they need to be kept or not because of my probable misunderstanding of treating these static variables).

**Comment by roystgnr** [comment]
> I need to get around to using clang more. I've avoided it because it's such a PITA to get libcxx built and used alongside it; our IT folks still have not moved away from CentOS 6, so the system libstdc++ is ancient

Before you go too far down that rabbit hole, from my September IM logs:

> (01:55:06 PM) Roy Stogner: FYI, don't expect a new clang any time soon.  I get a bunch of "undefined reference" errors when trying to link it using any version of gcc, and I get an "undeclared identifier" when trying to compile it using the CentOS7 clang.

I'm pretty happy with clang when it's up and running, but I was dumbfounded to see how hard it was to get there.  I even tried "bootstrapping" by building intermediate clang versions first with the intent of using them to build newer clang versions, but:

> (03:08:34 PM) Roy Stogner: bootstrapping didn't work - got clang through the compiler failures, but then it just hit the same linker failure as with gcc.
> (03:16:32 PM) Stewart Stafford: well, now what?
> (03:16:48 PM) Stewart Stafford: leave it be
> (03:17:06 PM) Stewart Stafford: not worth it like you said
> (03:21:12 PM) Roy Stogner: Well, one person hit the same bug: http://lists.llvm.org/pipermail/llvm-dev/2016-March/097716.html
> (03:21:58 PM) Roy Stogner: But the resolution was "just don't build libc++", which is like 25% giving up.
> (03:22:20 PM) Roy Stogner: That may be preferable to the current 100%-giving-up strategy, though, I suppose.
> (03:23:38 PM) Roy Stogner: The trouble is that the system libstdc++ is ancient, and if we build clang with a non-system libstdc++ then we have compiler modules on top of compiler modules and that way lies insanity.
> (05:05:29 PM) Stewart Stafford: that sounds awful for sure, let's not go that route

So I still can't run clang-format on my work computers, and @jwpeterson will continue to see MOOSE littered with commits like https://github.com/idaholab/moose/pull/10257/commits/1f7ec2120891be8c003b28a71ae196bebae37fb1 for the foreseeable future.

**Comment by pbauman** [comment]
Re: Stogner/Stafford log --- Yes, exactly. I've been avoiding that insanity, especially since I've been trying, with varying degrees of success to get my group to adopt using the [module system I've tried to setup](https://github.com/ubaceslab/swenv) (based off of what we were doing at ICES). I can only imagine the horror of trying to manage getting the extra linker flag in for libc++ instead of libstdc++. 

I need to try native Mac clang though. Maybe it's new enough now that I can just use it on the laptop to check compilation of libMesh, GRINS, Antioch, QUESO, etc.

**Comment by pbauman** [comment]
@brianmoose Is there any way to poke the PR or CIVET to have CIVET detect this PR since it didn't happen when @jwpeterson opened it?

**Comment by brianmoose** [comment]
Yes, on github, go to Settings -> Webhooks -> <your webhook>. There should be a list of events. Hopefully there is one that is red which is probably the failed event for the PR. Clicking on it shows the data so you can verify that it is the one you want. Then hit the "reddeliver" button. If it still fails then maybe you found a bug in CIVET, then please send me the response.

**Comment by pbauman** [comment]
> Yes, on github, go to Settings -> Webhooks -> . There should be a list of events. Hopefully there is one that is red which is probably the failed event for the PR. Clicking on it shows the data so you can verify that it is the one you want. Then hit the "reddeliver" button.

Perfect, that worked! Thanks!

**Comment by pbauman** [comment]
Cool, I'll go ahead and merge. Can clean up later if a redesign happens based on discussion in #510. Thanks @jwpeterson!

**Pull request merged**
