### PR TITLE
Fix compatibility with newer libmesh

### PR DESCRIPTION
**Pull request by roystgnr**
Tigher header refactoring in libMesh means we need a couple more direct parallel.h inclusions in GRINS, and the fix in https://github.com/libMesh/libmesh/pull/2504 caused a fraction of a percent difference in one of the GRINS regression tests.

@vikramvgarg has been adding better adjoint and sensitivity testing to libMesh proper, but it looks like the indirect test coverage of those features via GRINS still isn't redundant...

### CODE REVIEW

**Comment by pbauman** [comment]
I'm seeing one failure against this branch:

`FAIL: regression/extra_quadrature_order_laplace_arefee_amr.sh`

I'll attach the log file.

Module environment:
<pre>
Currently Loaded Modules:
  1) gcc/9.3.0   2) openblas/0.3.7   3) mpich/3.3.2   4) petsc/3.12.4-opt   5) hdf5/1.10.6   6) boost/1.66.0   7) vtk/8.2.0   8) cppunit/1.13.2   9) libmesh/master
</
[extra_quadrature_order_laplace_arefee_amr.sh.txt](https://github.com/grinsfem/grins/files/4659322/extra_quadrature_order_laplace_arefee_amr.sh.txt)
[extra_quadrature_order_laplace_arefee_amr.sh.txt](https://github.com/grinsfem/grins/files/4659325/extra_quadrature_order_laplace_arefee_amr.sh.txt)

pre>

Libmesh version:
<pre>
$LIBMESH_DIR/bin/output_libmesh_version-devel
--------------------------------------------------------
libMesh Library: Version = 1.6.0-pre (10600)



Build Date   = May 20 2020 15:55:30
Build Host   = fry
Build User   = pabauman
Build Arch   = x86_64-pc-linux-gnu
Build Rev    = 9006cd06b6a4d14f6e3238217a6261a551c1a519

--------------------------------------------------------
</pre>

GRINS git history:
<pre>
* ac20c8b4 - Wed, 20 May 2020 15:40:44 -0500 (28 minutes ago) (HEAD -> newer_libmesh, roystgnr/newer_libmesh)
|           Fix extra_quadrature_order_laplace_arefee_amr gold —Roy Stogner
* 4105e47f - Wed, 20 May 2020 15:38:02 -0500 (31 minutes ago)
|           Include libMesh parallel.h directly —Roy Stogner
</pre>

GRINS configure line:
<pre>
$ ../../grinsfem/configure --prefix=/home/pabauman/work/research/grins/install/devel METHOD=devel
</pre>

**Comment by pbauman** [comment]
For crying out loud, it's not letting put a file in. Here's the cat of the failing test log file.

<pre>
==========================================================
GRINS Version: ac20c8b4dca08ed937b4dc202d869bfe53d10c81
libMesh Version: 9006cd06b6a4d14f6e3238217a6261a551c1a519
Running with command:
/home/pabauman/work/research/grins/build/devel/test/.libs/generic_solution_regression --input ../../../grinsfem/test/input_files/extra_quadrature_order_laplace_arefee_amr_regression.in soln-data=../../../grinsfem/test/test_data/extra_quadrature_order_laplace_arefee_amr_regression.xdr vars=T norms=L2 H1 tol=1.0e-10 qois=-3.3294782502693245e+01 
==========================================================
==========================================================
List of Enabled Physics:
HeatConduction
ParsedSourceTerm
==========================================================
*** Warning, This code is deprecated, and likely to be removed in future library versions! /home/pabauman/software/sourcesdir/libmesh/libmesh-master/src/mesh/boundary_info.C, line 2057, compiled May 20 2020 at 15:56:02 ***
==========================================================
List of Enabled QoIs:
weighted_flux
==========================================================
 Mesh Information:
  elem_dimensions()={2}
  spatial_dimension()=2
  n_nodes()=289
    n_local_nodes()=289
  n_elem()=64
    n_local_elem()=64
    n_active_elem()=64
  n_subdomains()=1
  n_partitions()=1
  n_processors()=1
  n_threads()=1
  processor_id()=0

 EquationSystems
  n_systems()=1
   System #0, "GRINS"
    Type "Implicit"
    Variables="T" 
    Finite Element Types="LAGRANGE", "JACOBI_20_00" 
    Infinite Element Mapping="CARTESIAN" 
    Approximation Orders="SECOND", "THIRD" 
    n_dofs()=289
    n_local_dofs()=289
    n_constrained_dofs()=64
    n_local_constrained_dofs()=64
    n_vectors()=1
    n_matrices()=1
    DofMap Sparsity
      Average  On-Processor Bandwidth <= 14.6194
      Average Off-Processor Bandwidth <= 0
      Maximum  On-Processor Bandwidth <= 25
      Maximum Off-Processor Bandwidth <= 0
    DofMap Constraints
      Number of DoF Constraints = 64
      Average DoF Constraint Length= 0
      Number of Node Constraints = 0

==========================================================
Performing 5 adaptive refinements
==========================================================
==========================================================
Adaptive Refinement Step 0
==========================================================
Assembling the System
Nonlinear Residual: 540.559
Linear solve starting, tolerance 0.0001
Linear solve finished, step 12, residual 0.000154725
Trying full Newton step
  Current Residual: 0.0316012
  Nonlinear step: |du|/|u| = 1, |du| = 6.57247
Assembling the System
Nonlinear Residual: 0.0316012
Linear solve starting, tolerance 3.16012e-05
Linear solve finished, step 15, residual 2.90205e-09
Trying full Newton step
  Current Residual: 7.30862e-07
  Nonlinear step: |du|/|u| = 6.14095e-05, |du| = 0.000403611
Assembling the System
Nonlinear Residual: 7.30862e-07
Linear solve starting, tolerance 1e-06
Linear solve finished, step 18, residual 2.87298e-15
Trying full Newton step
  Current Residual: 6.71015e-13
  Nonlinear solver relative residual 1.24134e-15 > 1e-15
  Nonlinear solver converged, step 2, relative step size 1.03094e-09 < 1e-06
==========================================================
Estimating error
==========================================================
The flux QoI 0 is: 33.421

The error estimate for QoI(0) is: -0.106865
==========================================================
Checking convergence
==========================================================
==========================================================
Error estimate = 0.0622245
==========================================================
==========================================================
Performing Mesh Refinement
==========================================================
==========================================================
Refined mesh to           82 active elements
                         283 active dofs
==========================================================
==========================================================
weighted_flux = -3.3435864546527107e+01
==========================================================
==========================================================
Adaptive Refinement Step 1
==========================================================
Assembling the System
Nonlinear Residual: 4.8298030254277040e+02
Linear solve starting, tolerance 1.0000000000000000e-04
Linear solve finished, step 13, residual 8.7999678611165697e-05
Trying full Newton step
  Current Residual: 2.4669997450670757e-02
  Nonlinear step: |du|/|u| = 1.6338684899856076e-01, |du| = 1.4776527175974181e+00
Assembling the System
Nonlinear Residual: 2.4669997450670757e-02
Linear solve starting, tolerance 2.4669997450670759e-05
Linear solve finished, step 18, residual 1.6449047268424896e-09
Trying full Newton step
  Current Residual: 4.0294104080487754e-07
  Nonlinear step: |du|/|u| = 2.5679275011817233e-05, |du| = 2.3223860961843658e-04
Assembling the System
Nonlinear Residual: 4.0294104080487754e-07
Linear solve starting, tolerance 9.9999999999999995e-07
Linear solve finished, step 22, residual 9.4314844266253339e-16
Trying full Newton step
  Current Residual: 3.7987952160968315e-13
  Nonlinear solver converged, step 2, residual reduction 7.8653212068838536e-16 < 1.0000000000000001e-15
  Nonlinear solver converged, step 2, relative step size 9.1703160250378088e-10 < 9.9999999999999995e-07
==========================================================
Estimating error
==========================================================
The flux QoI 0 is: 3.3317312700308420e+01

The error estimate for QoI(0) is: -2.0712441940036241e-02
==========================================================
Checking convergence
==========================================================
==========================================================
Error estimate = 8.2321974377908627e-03
==========================================================
==========================================================
Performing Mesh Refinement
==========================================================
==========================================================
Refined mesh to          106 active elements
                         361 active dofs
==========================================================
==========================================================
weighted_flux = -3.3318572257752280e+01
==========================================================
==========================================================
Adaptive Refinement Step 2
==========================================================
Assembling the System
Nonlinear Residual: 3.0488879288018165e+02
Linear solve starting, tolerance 1.0000000000000000e-04
Linear solve finished, step 14, residual 9.4558343801875937e-05
Trying full Newton step
  Current Residual: 2.1667648799282825e-02
  Nonlinear step: |du|/|u| = 8.5189845624023694e-02, |du| = 9.1958270067684122e-01
Assembling the System
Nonlinear Residual: 2.1667648799282825e-02
Linear solve starting, tolerance 2.1667648799282827e-05
Linear solve finished, step 20, residual 1.7804667300292283e-09
Trying full Newton step
  Current Residual: 3.8012563633487675e-07
  Nonlinear step: |du|/|u| = 4.5150523402470101e-05, |du| = 4.8737147355324995e-04
Assembling the System
Nonlinear Residual: 3.8012563633487675e-07
Linear solve starting, tolerance 9.9999999999999995e-07
Linear solve finished, step 23, residual 1.4918625555174556e-15
Trying full Newton step
  Current Residual: 4.9022587754216600e-13
  Nonlinear solver relative residual 1.6078842154582574e-15 > 1.0000000000000001e-15
  Nonlinear solver converged, step 2, relative step size 7.1024002996267549e-10 < 9.9999999999999995e-07
==========================================================
Estimating error
==========================================================
The flux QoI 0 is: 3.3300965605886020e+01

The error estimate for QoI(0) is: -6.1978719581232966e-03
==========================================================
Checking convergence
==========================================================
==========================================================
Error estimate = 2.5295235599332002e-03
==========================================================
==========================================================
Performing Mesh Refinement
==========================================================
==========================================================
Refined mesh to          136 active elements
                         459 active dofs
==========================================================
==========================================================
weighted_flux = -3.3300965605886013e+01
==========================================================
==========================================================
Adaptive Refinement Step 3
==========================================================
Assembling the System
Nonlinear Residual: 3.3808130479194602e+02
Linear solve starting, tolerance 1.0000000000000000e-04
Linear solve finished, step 15, residual 7.9468694540022356e-05
Trying full Newton step
  Current Residual: 1.8814170483217051e-02
  Nonlinear step: |du|/|u| = 8.2589104745865324e-02, |du| = 1.0932076724126589e+00
Assembling the System
Nonlinear Residual: 1.8814170483217051e-02
Linear solve starting, tolerance 1.8814170483217051e-05
Linear solve finished, step 21, residual 1.4053145011390823e-09
Trying full Newton step
  Current Residual: 3.1500426518987854e-07
  Nonlinear step: |du|/|u| = 2.6959985761839043e-05, |du| = 3.5685937705916222e-04
Assembling the System
Nonlinear Residual: 3.1500426518987854e-07
Linear solve starting, tolerance 9.9999999999999995e-07
Linear solve finished, step 27, residual 8.2495038401221998e-16
Trying full Newton step
  Current Residual: 3.7511098097297393e-13
  Nonlinear solver relative residual 1.1095289081536639e-15 > 1.0000000000000001e-15
  Nonlinear solver converged, step 2, relative step size 6.0830673015131848e-10 < 9.9999999999999995e-07
==========================================================
Estimating error
==========================================================
The flux QoI 0 is: 3.3296202250510120e+01

The error estimate for QoI(0) is: -1.9146019237585282e-03
==========================================================
Checking convergence
==========================================================
==========================================================
Error estimate = 1.1801109239398669e-03
==========================================================
==========================================================
Performing Mesh Refinement
==========================================================
==========================================================
Refined mesh to          175 active elements
                         591 active dofs
==========================================================
==========================================================
weighted_flux = -3.3296194829393777e+01
==========================================================
==========================================================
Adaptive Refinement Step 4
==========================================================
Assembling the System
Nonlinear Residual: 5.7853078438300173e+01
Linear solve starting, tolerance 1.0000000000000000e-04
Linear solve finished, step 18, residual 1.5435115854746831e-05
Trying full Newton step
  Current Residual: 3.0120000593175538e-03
  Nonlinear step: |du|/|u| = 1.2322512805917849e-02, |du| = 1.7725977700169174e-01
Assembling the System
Nonlinear Residual: 3.0120000593175538e-03
Linear solve starting, tolerance 3.0120000593175539e-06
Linear solve finished, step 26, residual 4.0883984302507160e-11
Trying full Newton step
  Current Residual: 8.7147850693787845e-09
  Nonlinear step: |du|/|u| = 1.4984446821524642e-05, |du| = 2.1554931495575212e-04
Assembling the System
Nonlinear Residual: 8.7147850693787845e-09
Linear solve starting, tolerance 9.9999999999999995e-07
Linear solve finished, step 29, residual 4.0694915383916968e-17
Trying full Newton step
  Current Residual: 3.5925644277515411e-13
  Nonlinear solver relative residual 6.2098068499206678e-15 > 1.0000000000000001e-15
  Nonlinear solver converged, step 2, relative step size 1.7667061531058951e-11 < 9.9999999999999995e-07
==========================================================
Estimating error
==========================================================
The flux QoI 0 is: 3.3295495191687941e+01

The error estimate for QoI(0) is: -1.2615909945221230e-03
==========================================================
Checking convergence
==========================================================
==========================================================
Error estimate = 6.5082043667718484e-04
==========================================================
==========================================================
weighted_flux = -3.3295495191687948e+01
==========================================================
Assertion `n_assigned_vals == vector_length' failed.
n_assigned_vals = 811
vector_length = 855


Stack frames: 10
0: libMesh::print_trace(std::ostream&)
1: libMesh::MacroFunctions::report_error(char const*, int, char const*, char const*)
2: unsigned int libMesh::System::read_serialized_vector<double>(libMesh::Xdr&, libMesh::NumericVector<double>*)
3: void libMesh::System::read_serialized_data<double>(libMesh::Xdr&, bool)
4: void libMesh::EquationSystems::_read_impl<double>(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, libMesh::XdrMODE, unsigned int, bool)
5: void libMesh::EquationSystems::read<double>(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, libMesh::XdrMODE, unsigned int, bool)
6: void libMesh::EquationSystems::read<double>(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, unsigned int, bool)
7: /home/pabauman/work/research/grins/build/devel/test/.libs/generic_solution_regression() [0x404b0d]
8: __libc_start_main
9: /home/pabauman/work/research/grins/build/devel/test/.libs/generic_solution_regression() [0x40612a]
[0] /home/pabauman/software/sourcesdir/libmesh/libmesh-master/src/systems/system_io.C, line 1290, compiled May 20 2020 at 15:56:35

*********************************************************************
READING THE FILE "../../../grinsfem/test/test_data/extra_quadrature_order_laplace_arefee_amr_regression.xdr" FAILED.
It is possible this file contains infinite element information,
but the version string does not contain " with infinite elements"
Let's try this again, but looking for infinite element information...
*********************************************************************

Assertion `this->n_vars(s,vg) == nvpg[vg]' failed.
this->n_vars(s,vg) = 1
nvpg[vg] = 2


Stack frames: 15
0: libMesh::print_trace(std::ostream&)
1: libMesh::MacroFunctions::report_error(char const*, int, char const*, char const*)
2: libMesh::DofObject::set_n_vars_per_group(unsigned int, std::vector<unsigned int, std::allocator<unsigned int> > const&)
3: libMesh::DofMap::reinit(libMesh::MeshBase&)
4: libMesh::DofMap::distribute_dofs(libMesh::MeshBase&)
5: libMesh::System::init_data()
6: libMesh::ImplicitSystem::init_data()
7: libMesh::System::init()
8: libMesh::EquationSystems::init()
9: void libMesh::EquationSystems::_read_impl<double>(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, libMesh::XdrMODE, unsigned int, bool)
10: void libMesh::EquationSystems::read<double>(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, libMesh::XdrMODE, unsigned int, bool)
11: void libMesh::EquationSystems::read<double>(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, unsigned int, bool)
12: /home/pabauman/work/research/grins/build/devel/test/.libs/generic_solution_regression() [0x404b0d]
13: __libc_start_main
14: /home/pabauman/work/research/grins/build/devel/test/.libs/generic_solution_regression() [0x40612a]
[0] /home/pabauman/software/sourcesdir/libmesh/libmesh-master/src/base/dof_object.C, line 283, compiled May 20 2020 at 15:55:30

*********************************************************************
Well, at least we tried!
Good Luck!!
*********************************************************************


 --------------------------------------------------------------------------------------------------------------------------------------------
| Time:           Wed May 20 16:04:20 2020                                                                                                   |
| OS:             Linux                                                                                                                      |
| HostName:       fry                                                                                                                        |
| OS Release:     4.15.0-99-generic                                                                                                          |
| OS Version:     #100-Ubuntu SMP Wed Apr 22 20:32:56 UTC 2020                                                                               |
| Machine:        x86_64                                                                                                                     |
| Username:       pabauman                                                                                                                   |
| Configuration:  /home/pabauman/software/sourcesdir/libmesh/libmesh-master/configure  'METHODS=dbg devel opt'                               |
|  '--prefix=/home/pabauman/software/libs/libmesh/master/gcc/9.3.0/mpich/3.3.2/petsc/3.12.4/openblas/0.3.7/boost/1.66.0/hdf5/1.10.6/vtk/8.2.0'|
|  'CXX=mpicxx'                                                                                                                              |
|  'CC=mpicc'                                                                                                                                |
|  '--enable-everything'                                                                                                                     |
|  '--with-metis=PETSc'                                                                                                                      |
|  '--with-cppunit-prefix=/home/pabauman/software/libs/cppunit/1.13.2/gcc/9.3.0'                                                             |
|  '--disable-glibcxx-debugging'                                                                                                             |
|  '--with-vtk-lib=/home/pabauman/software/libs/vtk/8.2.0/gcc/9.3.0/mpich/3.3.2/lib'                                                         |
|  '--with-vtk-include=/home/pabauman/software/libs/vtk/8.2.0/gcc/9.3.0/mpich/3.3.2/include/vtk-8.2'                                         |
|  '--enable-hdf5'                                                                                                                           |
|  'PETSC_DIR=/home/pabauman/software/libs/petsc/3.12.4/gcc/9.3.0/mpich/3.3.2/openblas/0.3.7/opt'                                            |
|  'PETSC_ARCH='                                                                                                                             |
|  'FC=gfortran'                                                                                                                             |
|  'F77=gfortran'                                                                                                                            |
|  'VTK_INCLUDE=/home/pabauman/software/libs/vtk/8.2.0/gcc/9.3.0/mpich/3.3.2/include/vtk-8.2'                                                |
|  'VTK_DIR=/home/pabauman/software/libs/vtk/8.2.0/gcc/9.3.0/mpich/3.3.2'                                                                    |
|  'HDF5_DIR=/home/pabauman/software/libs/hdf5/1.10.6/gcc/9.3.0'                                                                             |
 --------------------------------------------------------------------------------------------------------------------------------------------
 ----------------------------------------------------------------------------------------------------------------------
| libMesh Performance: Alive time=9.05269, Active time=7.5883                                                          |
 ----------------------------------------------------------------------------------------------------------------------
| Event                                   nCalls     Total Time  Avg Time    Total Time  Avg Time    % of Active Time  |
|                                                    w/o Sub     w/o Sub     With Sub    With Sub    w/o S    With S   |
|----------------------------------------------------------------------------------------------------------------------|
|                                                                                                                      |
|                                                                                                                      |
| DefaultCoupling                                                                                                      |
|   operator()                            3553       0.0040      0.000001    0.0040      0.000001    0.05     0.05     |
|                                                                                                                      |
| DofMap                                                                                                               |
|   _node_dof_indices()                   9894       0.0020      0.000000    0.0020      0.000000    0.03     0.03     |
|   add_neighbors_to_send_list()          16         0.0000      0.000000    0.0000      0.000000    0.00     0.00     |
|   build_constraint_matrix()             11665      0.0124      0.000001    0.0124      0.000001    0.16     0.16     |
|   build_constraint_matrix_and_vector()  158        0.0004      0.000002    0.0004      0.000002    0.00     0.00     |
|   build_sparsity()                      16         0.0162      0.001016    0.0238      0.001490    0.21     0.31     |
|   cnstrn_elem_mat_vec()                 1689       0.0031      0.000002    0.0031      0.000002    0.04     0.04     |
|   constrain_elem_matrix()               2815       0.0027      0.000001    0.0027      0.000001    0.04     0.04     |
|   constrain_elem_vector()               4346       0.0017      0.000000    0.0017      0.000000    0.02     0.02     |
|   create_dof_constraints()              17         0.0277      0.001629    0.0982      0.005775    0.36     1.29     |
|   distribute_dofs()                     17         0.0121      0.000713    0.1092      0.006421    0.16     1.44     |
|   dof_indices()                         107907     0.0810      0.000001    0.0810      0.000001    1.07     1.07     |
|   enforce_adjoint_constraints_exactly() 19         0.0014      0.000073    0.0014      0.000073    0.02     0.02     |
|   enforce_constraints_exactly()         33         0.0019      0.000058    0.0019      0.000058    0.03     0.03     |
|   hetero_cnstrn_elem_vec()              158        0.0002      0.000001    0.0002      0.000001    0.00     0.00     |
|   old_dof_indices()                     64617      0.0498      0.000001    0.0498      0.000001    0.66     0.66     |
|   prepare_send_list()                   19         0.0000      0.000000    0.0000      0.000000    0.00     0.00     |
|   reinit()                              17         0.0970      0.005707    0.0970      0.005707    1.28     1.28     |
|                                                                                                                      |
| EquationSystems                                                                                                      |
|   read()                                2          0.0010      0.000504    0.0000      0.000000    0.01     0.00     |
|                                                                                                                      |
| FE                                                                                                                   |
|   compute_shape_functions()             40678      0.4649      0.000011    0.4649      0.000011    6.13     6.13     |
|   init_shape_functions()                31517      0.0235      0.000001    0.0235      0.000001    0.31     0.31     |
|                                                                                                                      |
| FEMSystem                                                                                                            |
|   assemble_qoi()                        5          0.0043      0.000858    0.0091      0.001815    0.06     0.12     |
|   assemble_qoi_derivative()             10         0.0318      0.003180    0.0521      0.005211    0.42     0.69     |
|   assembly()                            15         0.2903      0.019354    2.2507      0.150046    3.83     29.66    |
|   assembly(get_jacobian)                10         0.4741      0.047405    3.6605      0.366048    6.25     48.24    |
|   assembly(get_residual)                25         0.2779      0.011116    0.6108      0.024431    3.66     8.05     |
|   numerical_elem_jacobian()             4504       4.7918      0.001064    4.7918      0.001064    63.15    63.15    |
|   numerical_side_jacobian()             1452       0.0069      0.000005    0.0069      0.000005    0.09     0.09     |
|                                                                                                                      |
| FEMap                                                                                                                |
|   compute_affine_map()                  40678      0.0392      0.000001    0.0392      0.000001    0.52     0.52     |
|   compute_face_map()                    4096       0.0482      0.000012    0.1747      0.000043    0.63     2.30     |
|   init_face_shape_functions()           81         0.0002      0.000003    0.0002      0.000003    0.00     0.00     |
|   init_reference_to_physical_map()      31517      0.0472      0.000001    0.0472      0.000001    0.62     0.62     |
|   inverse_map()                         178499     0.4820      0.000003    0.4820      0.000003    6.35     6.35     |
|                                                                                                                      |
| GenericProjector                                                                                                     |
|   project                               74         0.0252      0.000340    0.3415      0.004615    0.33     4.50     |
|   project_edges                         74         0.0000      0.000000    0.0000      0.000000    0.00     0.00     |
|   project_interiors                     74         0.0061      0.000083    0.0823      0.001112    0.08     1.08     |
|   project_sides                         74         0.0146      0.000197    0.2066      0.002792    0.19     2.72     |
|   project_vertices                      74         0.0067      0.000091    0.0237      0.000320    0.09     0.31     |
|                                                                                                                      |
| ImplicitSystem                                                                                                       |
|   adjoint_solve()                       10         0.0003      0.000030    3.7938      0.379384    0.00     50.00    |
|                                                                                                                      |
| Mesh                                                                                                                 |
|   contract()                            14         0.0007      0.000049    0.0028      0.000198    0.01     0.04     |
|   find_neighbors()                      15         0.0077      0.000513    0.0077      0.000513    0.10     0.10     |
|   renumber_nodes_and_elem()             24         0.0021      0.000088    0.0021      0.000088    0.03     0.03     |
|                                                                                                                      |
| MeshBase                                                                                                             |
|   prepare_for_use()                     15         0.0021      0.000142    0.0244      0.001627    0.03     0.32     |
|   remove_orphaned_nodes()               10         0.0037      0.000369    0.0037      0.000369    0.05     0.05     |
|                                                                                                                      |
| MeshCommunication                                                                                                    |
|   assign_global_indices()               1          0.0058      0.005768    0.0058      0.005768    0.08     0.08     |
|                                                                                                                      |
| MeshRefinement                                                                                                       |
|   _coarsen_elements()                   23         0.0018      0.000078    0.0018      0.000078    0.02     0.02     |
|   _refine_elements()                    23         0.0027      0.000117    0.0115      0.000501    0.04     0.15     |
|   add_node()                            21600      0.0053      0.000000    0.0053      0.000000    0.07     0.07     |
|   make_coarsening_compatible()          36         0.0039      0.000107    0.0039      0.000107    0.05     0.05     |
|   make_flags_parallel_consistent()      28         0.0020      0.000072    0.0020      0.000072    0.03     0.03     |
|   make_refinement_compatible()          36         0.0001      0.000002    0.0001      0.000002    0.00     0.00     |
|                                                                                                                      |
| MeshTools                                                                                                            |
|   correct_node_proc_ids()               10         0.0108      0.001081    0.0108      0.001081    0.14     0.14     |
|                                                                                                                      |
| MeshTools::Generation                                                                                                |
|   build_cube()                          1          0.0003      0.000297    0.0003      0.000297    0.00     0.00     |
|                                                                                                                      |
| NewtonSolver                                                                                                         |
|   solve()                               5          0.0024      0.000482    2.5107      0.502149    0.03     33.09    |
|                                                                                                                      |
| OldSolutionBase                                                                                                      |
|   check_old_context(c,p)                27356      0.0211      0.000001    0.0993      0.000004    0.28     1.31     |
|                                                                                                                      |
| OldSolutionValue                                                                                                     |
|   Number eval_at_node()                 8872       0.0037      0.000000    0.0037      0.000000    0.05     0.05     |
|   eval_at_point()                       27356      0.0202      0.000001    0.2268      0.000008    0.27     2.99     |
|   eval_old_dofs(elem)                   1053       0.0001      0.000000    0.0001      0.000000    0.00     0.00     |
|   eval_old_dofs(node)                   4947       0.0010      0.000000    0.0034      0.000001    0.01     0.04     |
|                                                                                                                      |
| Partitioner                                                                                                          |
|   set_node_processor_ids()              9          0.0028      0.000314    0.0028      0.000314    0.04     0.04     |
|   single_partition_range()              5          0.0000      0.000009    0.0000      0.000009    0.00     0.00     |
|                                                                                                                      |
| PetscLinearSolver                                                                                                    |
|   solve()                               25         0.0901      0.003603    0.0901      0.003603    1.19     1.19     |
|                                                                                                                      |
| PointLocatorTree                                                                                                     |
|   init(no master)                       15         0.0087      0.000579    0.0087      0.000579    0.11     0.11     |
|                                                                                                                      |
| System                                                                                                               |
|   project_vector(old,new)               37         0.0334      0.000902    0.3856      0.010422    0.44     5.08     |
|                                                                                                                      |
| TopologyMap                                                                                                          |
|   init()                                23         0.0062      0.000269    0.0062      0.000269    0.08     0.08     |
 ----------------------------------------------------------------------------------------------------------------------
| Totals:                                 631964     7.5883                                          100.00            |
 ----------------------------------------------------------------------------------------------------------------------

application called MPI_Abort(MPI_COMM_WORLD, 1) - process 0
[unset]: write_line error; fd=-1 buf=:cmd=abort exitcode=1
:
system msg for write_line failure : Bad file descriptor
FAIL regression/extra_quadrature_order_laplace_arefee_amr.sh (exit status: 1)
</pre>

**Comment by pbauman** [comment]
I should've added that the test was run in serial.

**Comment by pbauman** [comment]
Looks like it's in the parsing of the output file in the tester program. Is there a write->read flag mismatch?

**Comment by roystgnr** [comment]
My new gold file isn't matching your mesh.  It's possible that we've got one of those AMR cases you *can't* use just a solution gold for, because slightly different solvers change the ordering of error indicators which changes the subsequent mesh.  I'm going to see if I can trigger the same error, and if I can then we'll need a more robust test - I guess just use generic_amr_testing_app instead of generic_solution_regression?

**Comment by pbauman** [comment]
> I guess just use generic_amr_testing_app instead of generic_solution_regression

Yes, one of my many embarrassments. I didn't get around to redoing all the tests to "Actually run the grins executable and then use a separate program to actually compare" vs. "Use some stupid single program that wasn't portable even across different physics". Let me know if you can reproduce and I'll help fix this test to be less stupid, at least.

**Comment by roystgnr** [comment]
Hmmm.  I can replicate the failure, but it might not be an AMR thing, it might be a subsequent change, after the post-2504 merge commit that I used to generate a new gold standard.  Trying to bisect *that* now.

**Comment by pbauman** [comment]
Damn. I never committed my `git bisect` script that would bisect libMesh using GRINS `make check` as the test. Need to create a devtools directory or something to put stuff like that.

**Comment by roystgnr** [comment]
> it might be a subsequent change, after the post-2504 merge commit that I used to generate a new gold standard.

And of course it was.  @vikramvgarg found and fixed another bug in libMesh/libmesh#2509 that affects adjoint refinement based AMR.  Let me try generating a new gold solution standard from *that* and then we can probably get away without having to use a gold mesh too.

**Comment by roystgnr** [comment]
Okay, try this one?

**Comment by pbauman** [comment]
Yup, looks good. Squash those last two commits and this is good to go.

**Pull request merged**
