### PR TITLE
Remove duplicate Viscosity objects

### PR DESCRIPTION
**Pull request by pbauman**
The Viscosity is in the incompressible_navier_stokes_base class. Thanks to @nicholasmalaya for the concise test input file. @nicholasmalaya, this should fix the problems you were seeing.

### CODE REVIEW

**Comment by pbauman** [comment]
I'll note it's annoying we didn't get shadow-type warnings. Thanks C++.

**Comment by pbauman** [comment]
@nicholasmalaya, let me know when you give this a whirl and I'll merge it.

**Comment by pbauman** [comment]
Rebased on master.

**Comment by nicholasmalaya** [comment]
Well, shit: 

<pre>
CXXLD    libgrins.la
/opt/apps/gcc/4.9.3/lib/gcc/x86_64-unknown-linux-gnu/4.9.3/../../../../x86_64-unknown-linux-gnu/bin/ld: cannot find                                     -lmpichf90_intel
collect2: error: ld returned 1 exit status
make[2]: *** [libgrins.la] Error 1
make[2]: Leaving directory `/work/00000/npm7/lonestar/paul_grins/build/src'
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory `/work/00000/npm7/lonestar/paul_grins/build'
make: *** [all] Error 2
make  install-recursive
make[1]: Entering directory `/work/00000/npm7/lonestar/paul_grins/build'
Making install in src
make[2]: Entering directory `/work/00000/npm7/lonestar/paul_grins/build/src'
  CXXLD    libgrins.la
/opt/apps/gcc/4.9.3/lib/gcc/x86_64-unknown-linux-gnu/4.9.3/../../../../x86_64-unknown-linux-gnu/bin/ld: cannot find                                     -lmpichf90_intel
collect2: error: ld returned 1 exit status
make[2]: *** [libgrins.la] Error 1
make[2]: Leaving directory `/work/00000/npm7/lonestar/paul_grins/build/src'
make[1]: *** [install-recursive] Error 1
make[1]: Leaving directory `/work/00000/npm7/lonestar/paul_grins/build'
make: *** [install] Error 2
</pre>

I'm getting similar errors to the older problem we had, despite the fact you said you rebased on master? Weird. I'm attaching the config.log but I don't seen an obvious reason its failing -- this is LS5 again.

[config.txt](https://github.com/grinsfem/grins/files/201566/config.txt)

**Comment by pbauman** [comment]
I'm stumped. Could you run your link again with `make V=1` so we can see the link line. Either there's a module you're missing (I'm guessing you'd already checked that) or libtool is stripping something. I checked your config.log and the `CXXFLAGS` are there.

**Comment by nicholasmalaya** [comment]
Not ignoring you. I'll send you this either tonight or tomorrow -- LS5 is down for maintenance here.

**Comment by nicholasmalaya** [comment]
Sigh, sorry for huge delay but I'm still getting issues here. I just tried to figure out what is going on for a good two hours and I have literally no idea. Is something different between this build system and the current base GRINS? Because I'm getting configuration errors on the GRINS master, though that is a different matter. 

I am attaching a config.log with make V=1 on, but its not really showing me what is even wrong here. 
[config.log.txt](https://github.com/grinsfem/grins/files/228362/config.log.txt) 

I'm slllliiightly worried that perhaps the modules under the hood might have changed, but perhaps that is just because I don't understand where these mpif90 flags are even necessary.

Sorry about the delay, I'll be more responsive, things were hectic. Would like to get this guy tested out and merged.

**Comment by pbauman** [comment]
Sorry, could you do `make V=1 2&>1 | tee make.log` and post make.log?

There is no change to the build system in this PR. That you're getting different behavior in the build between this branch and master is very strange.

I'm sorry I can't do more, but I don't have access to LS5 to try myself.

**Comment by nicholasmalaya** [comment]
No worries, you are being extremely helpful. I'm sorry I can't quite figure out what is even happening. 

make.log is attached, 
[make.log.txt](https://github.com/grinsfem/grins/files/228392/make.log.txt)

**Comment by roystgnr** [comment]
@nicholasmalaya, what's your "module list" say?

**Comment by nicholasmalaya** [comment]
@roystgnr 
<pre>
login1.ls5(87)$ module list

Currently Loaded Modules:
  1) intel/16.0.1   2) cray_mpich/7.3.0   3) TACC/1.0   4) autotools/1.1   5) git/2.6.4   6) boost/1.59   7) petsc/3.6
</pre>

**Comment by pbauman** [comment]
Thanks. It looks like the Fortran is getting sucked in because of phdf5. I'm not sure where in the software stack phdf5 is getting pulled in. Did they build PETSc with it? Did you build libMesh with it?

Maybe loading the appropriate phdf5 module gets that found? Or maybe the cray_mpich module was changed underneath you?

The sledge hammer solution here might be to forgo TACC's PETSc install and build your own and then use it with your libMesh build.

**Comment by roystgnr** [comment]
Weird.  Fortran should be a red herring, shouldn't it?  He's linking with "--mode=link mpicxx", which should add /opt/apps/intel16/cray_mpich/7.3.0/lib to the -L options given to g++, which should be enough for it to find /opt/apps/intel16/cray_mpich/7.3.0/lib/libmpichf90_intel.so

I can't argue with @pbauman's workaround, though.  Check out the configure options in /opt/apps/ossw/build_scripts/petsc on Sysnet if you have to do it yourself.

**Comment by roystgnr** [comment]
Weird.  Further down in that make.log.txt I see
```
libtool: link: g++ ...
```

That's not going to find the MPI libraries.  How does libtool get asked to use mpicxx and use g++ instead?

**Comment by pbauman** [comment]
> He's linking with "--mode=link mpicxx", which should add /opt/apps/intel16/cray_mpich/7.3.0/lib

Damn, after you said that I looked again. That first set of commands is what is passed to libtool What actually gets run is below that. I see now that it using `g++` and `mpicxx` to link. WTF.

**Comment by pbauman** [comment]
Crap. Ninja'ed by @roystgnr

**Comment by nicholasmalaya** [comment]
I noticed that as well, but isn't that just because it is trying to get at 'ld', and not actually using g++?

**Comment by pbauman** [comment]
@nicholasmalaya Can you try reconfiguring and adding `LD=mpicxx` to the configure line? I'm going to research this a bit more in the mean time.

**Comment by roystgnr** [comment]
It shouldn't be using ld to link either.  ld won't know about /whatever/stdc++/library the compiler assumed you'd be linking to.

**Comment by nicholasmalaya** [comment]
Hmm, it doesn't appear to respect LD=mpicxx, as I added it as below but the same error pops out(see attached make.log)
[make.log.txt](https://github.com/grinsfem/grins/files/228434/make.log.txt)

<pre>
It was created by grins configure 0.7.0, which was                                                                                                                                                                                            
generated by GNU Autoconf 2.69.  Invocation command line was                                                                                                                                                                                  
                                                                                                                                                                                                                                              
  $ ../configure --prefix=/work/00000/npm7/lonestar/LIBRARIES/2016-4-3-grins BOOST_DIR=/opt/apps/intel16/boost/1.59 LD=mpicxx CC=gcc MPICC=mpicc CXX=g++ MPICXX=mpicxx FC=mpif90 METHODS=opt --with-libmesh=/work/00000/npm7/lonestar/LIBRARI\
ES/2016-4-3-libmesh      
</pre>

**Comment by pbauman** [comment]
Just to make sure I'll be trying apples-to-apples, can you please post the output of `libtool --version`?

**Comment by pbauman** [comment]
Did you compile libMesh with `CXX=mpicxx CC=mpicc`?

**Comment by nicholasmalaya** [comment]
<pre>
login1.ls5(105)$ libtool --version
libtool (GNU libtool) 2.4.6
Written by Gordon Matzigkeit, 1996

Copyright (C) 2014 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
</pre>

To my surprise it is showing that I did not build libmesh with both CXX and CC specified. I wonder if I did previously and then removed that but I'm honestly not sure now. Try a rebuild with those specified? Sorry for the confusion.

**Comment by pbauman** [comment]
> To my surprise it is showing that I did not build libmesh with both CXX and CC specified

OK, cool, thanks.

> I wonder if I did previously and then removed that but I'm honestly not sure now. Try a rebuild with those specified?

No, if you're sure that you built libMesh without `CXX=mpicxx`, this should be fine. If you're not sure, try GRINS with `CXX=mpicxx and CC=mpicc`. My speculation is that, if you had built libMesh with that, that could be the problem because then libMesh might not see the MPI library path being a dependency since it was picked up `mpicxx` and then it's only using `CC` for the linking. I'm trying to figure out a way for us to always force using MPI for the linking step. libtool *does* use it for linking programs, but not for the library part (not sure why yet).

Also, I just noticed you have intel loading in your modules, but you're supplying `CC=gcc` and `CXX=g++`. In the absence of needing `CC=mpicc` as discussed above, you'd want `CC=icc` and CXX=`icpc`.

**Comment by pbauman** [comment]
> My speculation is that, if you had built libMesh with that, that could be the problem because then libMesh might not see the MPI library path being a dependency since it was picked up mpicxx and then it's only using CC for the linking.

OK, I don't think this is right. I just tried configuring locally and the dependency_libs have the MPI lib path in there regardless.

@nicholasmalaya could you post the dependency_libs variable in the $LIBMESH_DIR/lib/libmesh_opt.la please? I'm wondering if it somehow didn't get put in there?

**Comment by pbauman** [comment]
You should see something like the following

<pre>
# Libraries that this one depends upon.
dependency_libs=' -L/Users/pbauman/work/software/libs/hdf5/1.8.15-patch1/gcc/5.3.0/lib /Users/pbauman/work/software/libs/libmesh/master/gcc/5.3.0/mpich/3.1.4/petsc/3.5.4/openblas/0.2.14/tbb/4.3/boost/1.57.0/hdf5/1.8.15-patch1/vtk/6.2.0/lib/libnetcdf.la /Users/pbauman/work/software/libs/hdf5/1.8.15-patch1/gcc/5.3.0/lib/libhdf5_hl.la -lcurl -L/Users/pbauman/work/software/libs/vtk/6.2.0/lib -L/Users/pbauman/work/software/libs/tbb/4.3/gcc/5.3.0/lib -L/Users/pbauman/work/software/libs/petsc/3.5.4/gcc/5.3.0/mpich/3.1.4/openblas/0.2.14/opt/lib -L/Users/pbauman/work/software/libs/mpich/3.1.4/gcc/5.3.0/lib -L/Users/pbauman/work/software/apps/gcc/5.3.0/lib/gcc/x86_64-apple-darwin14.5.0/5.3.0 -L/Users/pbauman/work/software/apps/gcc/5.3.0/lib -L/Users/pbauman/work/software/libs/openblas/0.2.14/gcc/5.3.0/lib -L/opt/X11/lib -L/Users/pbauman/work/software/builddir/gcc-TfVcW7/x86_64-apple-darwin14.5.0/libstdc++-v3/src -L/Users/pbauman/work/software/builddir/gcc-TfVcW7/x86_64-apple-darwin14.5.0/libstdc++-v3/src/.libs -L/Users/pbauman/work/software/builddir/gcc-TfVcW7/x86_64-apple-darwin14.5.0/libstdc++-v3/libsupc++/.libs /Users/pbauman/work/software/libs/hdf5/1.8.15-patch1/gcc/5.3.0/lib/libhdf5.la -lvtkIOCore-6.2 -lvtkCommonCore-6.2 -lvtkCommonDataModel-6.2 -lvtkFiltersCore-6.2 -lvtkIOXML-6.2 -lvtkImagingCore-6.2 -lvtkIOImage-6.2 -lvtkImagingMath-6.2 -lvtkIOParallelXML-6.2 -lz -ltbb -ltbbmalloc -lpetsc -lHYPRE -lcmumps -ldmumps -lsmumps -lzmumps -lmumps_common -lpord -lscalapack -lsuperlu_4.3 -lsuperlu_dist_3.3 -lopenblas -lparmetis -lmetis -lX11 -lssl -lcrypto /Users/pbauman/work/software/libs/mpich/3.1.4/gcc/5.3.0/lib/libmpifort.la /Users/pbauman/work/software/apps/gcc/5.3.0/lib/libgfortran.la /Users/pbauman/work/software/apps/gcc/5.3.0/lib/libquadmath.la /Users/pbauman/work/software/libs/mpich/3.1.4/gcc/5.3.0/lib/libmpicxx.la /Users/pbauman/work/software/apps/gcc/5.3.0/lib/libstdc++.la -lm /Users/pbauman/work/software/libs/mpich/3.1.4/gcc/5.3.0/lib/libmpi.la /Users/pbauman/work/software/libs/mpich/3.1.4/gcc/5.3.0/lib/libpmpi.la -lpthread -lSystem -lgcc_ext.10.5 -ldl'
</pre>

**Comment by nicholasmalaya** [comment]
Here is the dependency_libs var
<pre>
# Libraries that this one depends upon.
dependency_libs=' /work/00000/npm7/LIBRARIES/2016-1-5-libmesh/lib/libnetcdf.la -lcurl /opt/apps/gcc/4.9.3/lib/../lib64/libstdc++.la -L/opt/apps/intel16/cray_mpich_7_3/petsc/3.6/haswell/lib -L/opt/apps/gcc/4.9.3/lib/gcc/x86_64-unknown-linux-gnu/4.9.3 -L/opt/apps/gcc/4.9.3/lib64 -L/opt/apps/gcc/4.9.3/x86_64-unknown-linux-gnu/lib -L/opt/apps/gcc/4.9.3/lib -L/opt/apps/intel16/cray_mpich_7_2/phdf5/1.8.16/x86_64/lib -lpetsc -lcmumps -ldmumps -lsmumps -lzmumps -lmumps_common -lpord -lscalapack -lHYPRE -lspai -lml -lmkl_intel_lp64 -lmkl_sequential -lmkl_core -lparmetis -lmetis /opt/apps/intel16/cray_mpich_7_2/phdf5/1.8.16/x86_64/lib/libhdf5hl_fortran.la /opt/apps/intel16/cray_mpich_7_2/phdf5/1.8.16/x86_64/lib/libhdf5_fortran.la /opt/apps/intel16/cray_mpich_7_2/phdf5/1.8.16/x86_64/lib/libhdf5_hl.la /opt/apps/intel16/cray_mpich_7_2/phdf5/1.8.16/x86_64/lib/libhdf5.la /opt/apps/intel16/cray_mpich_7_2/phdf5/1.8.16/x86_64/lib/libsz.la -lz -lssl -lcrypto -lchaco -lhwloc -lmpichf90_intel -lifport -lifcore_pic -lirc /opt/apps/gcc/4.9.3/lib/../lib64/libcilkrts.la /opt/apps/gcc/4.9.3/lib/../lib64/libstdc++.la /opt/apps/gcc/4.9.3/lib/../lib64/libstdc++.la'
</pre>

So it is linking against the cray_mpich, no mpifort.

**Comment by pbauman** [comment]
OK, so there's the problem from the GRINS side (until I can figure out how to force the linker). libMesh did not pick up the lib directory for MPI. I wonder why that is?

@roystgnr is the MPI location snooped from PETSc?

**Comment by roystgnr** [comment]
MPI is snooped from PETSc whenever PETSc is detected and not disabled, yes.  But typically the MPI_LIB variable in PETSc's config is empty, because that all gets pulled in by mpicc and mpicxx.

**Comment by pbauman** [comment]
Hmmm. On my system, the `Libs.private` variable in $PETSC_DIR/lib/pkgconfig/PETSc.pc has all the compiler, MPI, etc. paths in it and matches what's in my local libmesh.la dependencies variable. I wonder what's happening differently on LS5. I'll keep poking around on my end.

**Comment by pbauman** [comment]
OK, I'm having trouble figuring out how to make `libtool` do what I want it to do. (Indeed [this very thing](https://lists.gnu.org/archive/html/libtool/2012-05/msg00002.html) has come up already with no answer.) I'm leaning towards just having the GRINS build system supply the MPI paths and, if they turn out to be duplicate, libtool will strip them anyway. Thoughts @roystgnr?

**Comment by pbauman** [comment]
Oh, BTW @nicholasmalaya, to try and get you running sooner, you ought to be able to drop `LDFLAGS=-L/path/to/mpi/libs` on your configure line and get around this.

**Comment by nicholasmalaya** [comment]
OK! Adding:
<pre>
LDFLAGS=-L/opt/cray/mpt/7.3.0/gni/mpich-intel/14.0/lib
</pre>

to my configure script does get things building. I'm queuing up a few jobs to see if this looks good and will update this ticket with the results (as well as if we can get back to the original subject of this merge) when I have them tomorrow AM. I'm going to crash in the meantime, thanks for the help.

**Comment by nicholasmalaya** [comment]
I'm getting the following error if I specify the viscosity as part of the 'gas' phase object. 
<pre>
Error: Must specify parsed function for ParsedViscosity                                                                                                                                                                                       
       Please specify Materials/Viscosity/mu       
</pre>

My viscosity in the input looks like, 
<pre>
[Materials]
   [./Gas]
     [./Viscosity]
         model = 'parsed'
         value = 'z+.31382'   #[kg/m-s]
      [../Density]
	 value = '1.225'            #[kg/m^3]
      [../ThermalConductivity]
         model = 'parsed'
         value = 'z+17000*2.624e-2' #[W/m-K] 
      [../SpecificHeat]
         model = 'constant'
         value =  '1004.9'
      [../ReferenceTemperature]
          value = '288.0'  # [K]
      [../ThermalExpansionCoeff]
         value = '0.00255' # [1/K]
[]                                                          
 </pre>

Which I had thought was how we should declare it, given the examples I've found. If I move the viscosity out of 'gas' into the materials, then I get an error stating that,
<pre>
Error: Could not find Materials/Gas/Viscosity/model in input file. 
</pre>

I guess I don't know where to put the Viscosity block? Thanks for any pointers.

**Comment by pbauman** [comment]
Hmmm. Let me see if I missed something. Is this with the test input file you'd sent me way-back-when?

**Comment by pbauman** [comment]
Can you post the stack trace? I cannot reproduce this and I don't see how it's possible for you to get this just looking at the code.

**Comment by pbauman** [comment]
"This" means the first error message you posted:

<pre>
Error: Must specify parsed function for ParsedViscosity                                                                                                                                                                                       
       Please specify Materials/Viscosity/mu
</pre>

**Comment by nicholasmalaya** [comment]
Here is the traceout from proc 0: [traceout_0_42963.txt](https://github.com/grinsfem/grins/files/232631/traceout_0_42963.txt)

However, this is not a nice paired down example -- this was running on LS5 in parallel. I had just assumed I had the input file was wrong and it was a quick fix. It is valuable to me knowing that my code block is not obviously insane. I'll take a quick swing at seeing if I can discover what is wrong. My plan at this point is to:

1) Check my libmesh build is up to date (we have seen similar funkyness like this before...)
2) Try to reproduce this on the paired down (ideally, serial) example

Any other ideas are welcome, in lieu of that I'll update after I hit those bases and report back.

**Comment by pbauman** [comment]
That stack trace looks like you weren't using this branch.

<pre>
#6  0x00002aaaac68551d in GRINS::ParameterUser::set_parameter(libMesh::ParsedFunction<double, libMesh::VectorValue<double> >&, GetPot const&, std::string const&, std::string const&) () from /work/00000/npm7/lonestar/LIBRARIES/2016-3-21-grins/lib/libgrins.so.0
#7  0x00002aaaac6231ea in GRINS::ParsedViscosity::ParsedViscosity(GetPot const&) () from /work/00000/npm7/lonestar/LIBRARIES/2016-3-21-grins/lib/libgrins.so.0
#8  0x00002aaaac591e9a in GRINS::VelocityPenaltyAdjointStabilization<GRINS::ParsedViscosity>::VelocityPenaltyAdjointStabilization(std::string const&, GetPot const&) () from /work/00000/npm7/lonestar/LIBRARIES/2016-3-21-grins/lib/libgrins.so.0
</pre>

`VelocityPenaltyAdjointStabilization` as of this PR no longer owns a `Viscosity` object... You sure you're using the branch you think you're using?

**Comment by nicholasmalaya** [comment]
Well that is great info. I have no clue how I might *not* be using the latest branch, but worth really digging down to see if it is sneaking in somehow.

**Comment by pbauman** [comment]
Not at all trying to be insulting, but remember this is not master (since this isn't merged), but pbauman/dup-visc-fixes.

**Comment by nicholasmalaya** [comment]
Not insulted at all, it is an easy mistake to make and I want to run, I don't care if you have to carry me across the line :P  -- But I must have checked this 1000x by now.

**Comment by nicholasmalaya** [comment]
OK -- we are off to the races. I must have had some weird cruft in a build. A completely clean install is now running successfully with no viscosity input warnings!

Whew. Long road, sorry for all the winding paths. I recommend this for merging to master.

**Comment by pbauman** [comment]
Great, thanks!

**Pull request merged**
