### PR TITLE
VelocityPenalty2 distinct postprocessing names

### PR DESCRIPTION
**Pull request by roystgnr**
This should hopefully fix the bug @nicholasmalaya encountered this afternoon.

### CODE REVIEW

**Comment by pbauman** [comment]
Sorry bout that. Merge whenever you're ready.

**Comment by roystgnr** [comment]
No problem.  It might have been a bug pre-postprocessing-refactor too (I don't recall ever testing the vel_penalty outputs with VelocityPenalty2 active), and the refactor certainly made it easy to fix.

Going to hold off on merge until Nick's done a proper test run + viz; all I verified was that his original buggy case no longer throws an error.

**Comment by roystgnr** [comment]
Rebasing so Nick can build on lonestar

**Comment by roystgnr** [comment]
Rebased again to incorporate #208.  As soon as I verify that that fixes the last of the postprocessing weirdness I'll merge.

**Pull request merged**
