### PR TITLE
Spalart allmaras

### PR DESCRIPTION
**Pull request by vikramvgarg**
Spalart Allmaras turbulence model and turbulent viscosity capability added

### CODE REVIEW

**Comment by pbauman** [comment]
I'd still like to have *some* kind of test (and preferably example as well) that uses this so we can track changes, etc. We can always add MASA tests later, but until we have those, then we should at least be able to have something illustrating that this passes the eyeball norm test.

**Comment by vikramvgarg** [comment]
Ok, I think Todd had some ideas about this, I will talk to him about it.

On Tue, Jan 6, 2015 at 7:23 PM, Paul T. Bauman <notifications@github.com>
wrote:

> I'd still like to have *some* kind of test (and preferably example as
> well) that uses this so we can track changes, etc. We can always add MASA
> tests later, but until we have those, then we should at least be able to
> have something illustrating that this passes the eyeball norm test.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/grinsfem/grins/pull/186#issuecomment-68965032>.
>



-- 
Vikram Garg
Postdoctoral Associate
Predictive Engineering and Computational Science (PECOS)
The University of Texas at Austin
http://web.mit.edu/vikramvg/www/

http://www.runforindia.org/runners/vikramg

**Comment by pbauman** [comment]
If there is no such case that runs without stabilization, that's fine, we can wait to merge this until there's stabilization (which you can just push to this branch, if you want).

**Comment by vikramvgarg** [comment]
Well, now that I think about it, there should certainly be a manufactured
solution than can be created for the non-stabilized SA model. This wont
simulate the kind of cases the model is actually used for (which always use
stabilization) but our goal here is verification, not validation, so that
shouldnt matter.

In light of this, it certainly makes more sense to keep the stabilized and
non-stabilized versions separate as is done for the Incompressible NS, and
as you mentioned that also makes more sense from the point of view of the
different types of stabilization one can use.

I'll add the stabilization framework and a SPGSM stabilized version and put
it in this pull request.

Thanks.

On Wed, Jan 7, 2015 at 11:05 AM, Paul T. Bauman <notifications@github.com>
wrote:

> If there is no such case that runs without stabilization, that's fine, we
> can wait to merge this until there's stabilization (which you can just push
> to this branch, if you want).
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/grinsfem/grins/pull/186#issuecomment-69053838>.
>



-- 
Vikram Garg
Postdoctoral Associate
Predictive Engineering and Computational Science (PECOS)
The University of Texas at Austin
http://web.mit.edu/vikramvg/www/

http://www.runforindia.org/runners/vikramg

**Comment by pbauman** [comment]
I'm all for getting the MASA case going, don't get me wrong. Just wasn't sure which was the quicker path to victory. If you want to hook up MASA for a reasonable (not necessarily physical) case, go for it.

**Comment by pbauman** [comment]
@vikramvgarg Regarding your query in  25f8394 you need to subclass the `BCFactory`, override the `build_dirichlet()` method, and add your new bc factory to the `SimulationBuilder`. Checkout `test/test_ns_poiseuille_flow.C` for an example. Note you use the `DBCContainer` object to set everything, GRINS will take care of interfacing with libMesh behind the scenes. Note for the `DBCContainer` object, you can only set one function per object, but you can associate many bc_ids and variables with that function.

**Comment by vikramvgarg** [comment]
Thanks Paul, my boundary condition specification needs access to a
MeshFunction object which is most naturally constructed in main(). Will I
pass a MeshFunction pointer to the build_dirichlet function belonging to
class TurbulentBCFactory : public GRINS::BoundaryConditionsFactory ?

On Fri, Mar 6, 2015 at 6:16 AM, Paul T. Bauman <notifications@github.com>
wrote:

> @vikramvgarg <https://github.com/vikramvgarg> Regarding your query in
> 25f8394
> <https://github.com/grinsfem/grins/commit/25f8394a556b840f5b1a4504ac694757cb6cf17a>
> you need to subclass the BCFactory, override the build_dirichlet()
> method, and add your new bc factory to the SimulationBuilder. Checkout
> test/test_ns_poiseuille_flow.C for an example. Note you use the
> DBCContainer object to set everything, GRINS will take care of
> interfacing with libMesh behind the scenes. Note for the DBCContainer
> object, you can only set one function per object, but you can associate
> many bc_ids and variables with that function.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/grinsfem/grins/pull/186#issuecomment-77550472>.
>



-- 
Vikram Garg
Postdoctoral Associate
Predictive Engineering and Computational Science (PECOS)
The University of Texas at Austin
http://web.mit.edu/vikramvg/www/

http://www.runforindia.org/runners/vikramg

**Comment by pbauman** [comment]
We might need to update the build_dirichlet API such that you'd be able to construct your MeshFunction. For now, pass whatever you need to the TurbulentBCFactory constructor.

**Comment by vikramvgarg** [comment]
There are two variables for which I need to set the inlet bcs. One belongs
to the incompressible navier stokes physics, and the other to the spalart
allmaras physics. Will I need two separate bc_factory objects to do this ?

Or can I put two maps in the mymap in build_dirichlet() ?

On Fri, Mar 6, 2015 at 10:31 AM, Paul T. Bauman <notifications@github.com>
wrote:

> We might need to update the build_dirichlet API such that you'd be able to
> construct your MeshFunction. For now, pass whatever you need to the
> TurbulentBCFactory constructor.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/grinsfem/grins/pull/186#issuecomment-77588657>.
>



-- 
Vikram Garg
Postdoctoral Associate
Predictive Engineering and Computational Science (PECOS)
The University of Texas at Austin
http://web.mit.edu/vikramvg/www/

http://www.runforindia.org/runners/vikramg

**Comment by pbauman** [comment]
You set the physics when you insert the map

**Comment by vikramvgarg** [comment]
I think I am almost there. The only thing that remains is passing a
TurbulentBdyFunction to the DBC container.

In the other examples you have passed
a std::tr1::shared_ptr<libMesh::FunctionBase<libMesh::Number> > vel_func(
new GRINS::SomeVelocityProfile ) as the argument.

I need to pass a TurbulentBdyFunction, which is of
type  TurbulentBdyFunction : public libMesh::FunctionBase<libMesh::Number>

Something along the lines of:

TurbulentBdyFunction turbulent_inlet(this->turbulent_bc_values);

  GRINS::DBCContainer cont_u;
  cont_u.add_var_name( "u" );
  cont_u.add_bc_id( 0 );

  cont_u.set_func( turbulent_inlet );

But this gives me an error that set_func doesnt accept a
TurbulentBdyFunction as an argument. Should I cast turbulent_inlet as a
shared_ptr ?



On Fri, Mar 6, 2015 at 5:48 PM, Paul T. Bauman <notifications@github.com>
wrote:

> You set the physics when you insert the map
>
> > On Mar 6, 2015, at 5:13 PM, vikramvgarg <notifications@github.com>
> wrote:
> >
> > There are two variables for which I need to set the inlet bcs. One
> belongs
> > to the incompressible navier stokes physics, and the other to the spalart
> > allmaras physics. Will I need two separate bc_factory objects to do this
> ?
> >
> > Or can I put two maps in the mymap in build_dirichlet() ?
> >
> > On Fri, Mar 6, 2015 at 10:31 AM, Paul T. Bauman <
> notifications@github.com>
> > wrote:
> >
> > > We might need to update the build_dirichlet API such that you'd be
> able to
> > > construct your MeshFunction. For now, pass whatever you need to the
> > > TurbulentBCFactory constructor.
> > >
> > > —
> > > Reply to this email directly or view it on GitHub
> > > <https://github.com/grinsfem/grins/pull/186#issuecomment-77588657>.
> > >
> >
> >
> >
> > --
> > Vikram Garg
> > Postdoctoral Associate
> > Predictive Engineering and Computational Science (PECOS)
> > The University of Texas at Austin
> > http://web.mit.edu/vikramvg/www/
> >
> > http://www.runforindia.org/runners/vikramg
> > —
> > Reply to this email directly or view it on GitHub.
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/grinsfem/grins/pull/186#issuecomment-77657407>.
>



-- 
Vikram Garg
Postdoctoral Associate
Predictive Engineering and Computational Science (PECOS)
The University of Texas at Austin
http://web.mit.edu/vikramvg/www/

http://www.runforindia.org/runners/vikramg

**Comment by pbauman** [comment]
```
//! Add the Dirichlet bc functor
/*! There is only one Dirichlet bc functor for each container object */
void set_func( std::tr1::shared_ptr<libMesh::FunctionBase<libMesh::Number> > func );
```

So you need to so something like `std::tr1::shared_ptr<libMesh::FunctionBase<libMesh::Number> >( new TurbulentBdyFunction(this->turbulent_bc_values) );`

**Comment by vikramvgarg** [comment]
I finally have the test running but it seems to be still using the boundary
conditions from the input file. I checked that the attachment of bc_factory
is done as in the stokes_poiseuille test.

On Sat, Mar 7, 2015 at 7:42 AM, Paul T. Bauman <notifications@github.com>
wrote:

> //! Add the Dirichlet bc functor
> /*! There is only one Dirichlet bc functor for each container object */
> void set_func( std::tr1::shared_ptr<libMesh::FunctionBase<libMesh::Number> > func );
>
> So you need to so something like std::tr1::shared_ptr<libMesh::FunctionBase<libMesh::Number>
> >( new TurbulentBdyFunction(this->turbulent_bc_values) );
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/grinsfem/grins/pull/186#issuecomment-77689746>.
>



-- 
Vikram Garg
Postdoctoral Associate
Predictive Engineering and Computational Science (PECOS)
The University of Texas at Austin
http://web.mit.edu/vikramvg/www/

http://vikramvgarg.wordpress.com/
http://www.runforindia.org/runners/vikramg

**Comment by pbauman** [comment]
Since you started working on #203, does that mean we should start meting from master, cleaning this up, etc.?

**Comment by vikramvgarg** [comment]
Not until the end of the week. Need to get a test case verified by Friday
and show adjoint sensitivity calculation capability.

On Sat, Mar 14, 2015 at 9:01 AM, Paul T. Bauman <notifications@github.com>
wrote:

> Since you started working on #203
> <https://github.com/grinsfem/grins/issues/203>, does that mean we should
> start meting from master, cleaning this up, etc.?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/grinsfem/grins/pull/186#issuecomment-80499691>.
>



-- 
Vikram Garg
Postdoctoral Associate
Predictive Engineering and Computational Science (PECOS)
The University of Texas at Austin
http://web.mit.edu/vikramvg/www/

http://vikramvgarg.wordpress.com/
http://www.runforindia.org/runners/vikramg

**Comment by pbauman** [comment]
Your test_turbulent_channel case is failing because there is no file `test_data/turbulent_channel_Re944_grid.xda`. Did you forget to add it? Go ahead and push it to this branch and I'll fetch from there.

**Comment by vikramvgarg** [comment]
The grid and solution file have been pushed in.

On Wed, Apr 1, 2015 at 3:47 PM, Paul T. Bauman <notifications@github.com>
wrote:

> Your test_turbulent_channel case is failing because there is no file
> test_data/turbulent_channel_Re944_grid.xda. Did you forget to add it? Go
> ahead and push it to this branch and I'll fetch from there.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/grinsfem/grins/pull/186#issuecomment-88627054>.
>



-- 
Vikram Garg
Postdoctoral Associate
Predictive Engineering and Computational Science (PECOS)
The University of Texas at Austin
http://web.mit.edu/vikramvg/www/

http://vikramvgarg.wordpress.com/
http://www.runforindia.org/runners/vikramg

**Comment by pbauman** [comment]
Thanks. I pulled and am now tripping an assert:

```
[05:12:58][pbauman@fry:/fry1/data/users/pbauman/research/grins/build/spalart_allmaras/devel/test]$ ./test_turbulent_channel.sh 
 EquationSystems
  n_systems()=1
   System #0, "flow"
    Type "Implicit"
    Variables={ "u" "nutil" } 
    Finite Element Types="LAGRANGE", "JACOBI_20_00" 
    Infinite Element Mapping="CARTESIAN" 
    Approximation Orders="FIRST", "THIRD" 
    n_dofs()=662
    n_local_dofs()=662
    n_constrained_dofs()=0
    n_local_constrained_dofs()=0
    n_vectors()=2
    n_matrices()=1
    DofMap Sparsity
      Average  On-Processor Bandwidth <= 5.98792
      Average Off-Processor Bandwidth <= 0
      Maximum  On-Processor Bandwidth <= 6
      Maximum Off-Processor Bandwidth <= 0
    DofMap Constraints
      Number of DoF Constraints = 0
      Number of Node Constraints = 0

No of walls: 2
Boundary Id: 0
Boundary Id: 2
No of walls: 2
Boundary Id: 0
Boundary Id: 2
==========================================================
List of Enabled Physics:
IncompressibleNavierStokes
IncompressibleNavierStokesSPGSMStabilization
SpalartAllmaras
SpalartAllmarasSPGSMStabilization
==========================================================
Assertion `belem->default_order() == FIRST' failed.
[Thread debugging using libthread_db enabled]
0x00000038b76ac65d in waitpid () from /lib64/libc.so.6
To enable execution of this file add
	add-auto-load-safe-path /fry1/data/shared/software/apps/gcc/4.8.4/lib64/libstdc++.so.6.0.19-gdb.py
line to your configuration file "/eng/home/pbauman/.gdbinit".
To completely disable this security protection add
	set auto-load safe-path /
line to your configuration file "/eng/home/pbauman/.gdbinit".
For more information about this security protection see the
"Auto-loading safe path" section in the GDB manual.  E.g., run from the shell:
	info "(gdb)Auto-loading safe path"
#0  0x00000038b76ac65d in waitpid () from /lib64/libc.so.6
#1  0x00000038b763e609 in do_system () from /lib64/libc.so.6
#2  0x00000038b763e940 in system () from /lib64/libc.so.6
#3  0x00007f58c23489a5 in libMesh::print_trace(std::basic_ostream<char, std::char_traits<char> >&) () at src/base/print_trace.C:137
#4  0x00007f58c2346f34 in libMesh::MacroFunctions::report_error(char const*, int, char const*, char const*) () at src/base/libmesh_common.C:70
#5  0x00007f58c3742e08 in GRINS::DistanceFunction::node_to_boundary(libMesh::Node const*) () at ../../../../pbauman/src/utilities/src/distance_function.C:259
#6  0x00007f58c3744c5d in GRINS::DistanceFunction::compute() () at ../../../../pbauman/src/utilities/src/distance_function.C:594
#7  0x00007f58c2a10e67 in libMesh::EquationSystems::init() () at src/systems/equation_systems.C:121
#8  0x00007f58c370aa35 in GRINS::Solver::initialize(GetPot const&, boost::shared_ptr<libMesh::EquationSystems>, GRINS::MultiphysicsSystem*) () at ../../../../pbauman/src/solver/src/grins_solver.C:74
#9  0x00007f58c3718b53 in GRINS::Simulation::Simulation(GetPot const&, GRINS::SimulationBuilder&, libMesh::Parallel::Communicator const&) () at ../../../../pbauman/src/solver/src/simulation.C:80
#10 0x000000000041efab in main () at ../../../../pbauman/test/test_turbulent_channel.C:254
[0] ../../../../pbauman/src/utilities/src/distance_function.C, line 259, compiled Apr  1 2015 at 16:34:24
```

Perhaps a fix that you didn't push?

**Comment by pbauman** [comment]
Note I haven't merged yet - I was getting your test running with VPATH builds first, then was going to merge and clean up.

**Comment by vikramvgarg** [comment]
Yes, the DistanceFunction does not support second order approximation yet,
so changing V_ORDER to FIRST in the turbulent_channel_input.in will fix
this.

On Wed, Apr 1, 2015 at 4:15 PM, Paul T. Bauman <notifications@github.com>
wrote:

> Note I haven't merged yet - I was getting your test running with VPATH
> builds first, then was going to merge and clean up.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/grinsfem/grins/pull/186#issuecomment-88633868>.
>



-- 
Vikram Garg
Postdoctoral Associate
Predictive Engineering and Computational Science (PECOS)
The University of Texas at Austin
http://web.mit.edu/vikramvg/www/

http://vikramvgarg.wordpress.com/
http://www.runforindia.org/runners/vikramg

**Comment by pbauman** [comment]
All variable orders in the input file are FIRST and I still trip the same assert.

**Comment by vikramvgarg** [comment]
Sorry, you also had to change element_type to QUAD4.

On Wed, Apr 1, 2015 at 4:23 PM, Paul T. Bauman <notifications@github.com>
wrote:

> All variable orders in the input file are FIRST and I still trip the same
> assert.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/grinsfem/grins/pull/186#issuecomment-88635354>.
>



-- 
Vikram Garg
Postdoctoral Associate
Predictive Engineering and Computational Science (PECOS)
The University of Texas at Austin
http://web.mit.edu/vikramvg/www/

http://vikramvgarg.wordpress.com/
http://www.runforindia.org/runners/vikramg

**Comment by pbauman** [comment]
This the solution you're expecting?

sa_channel

**Comment by pbauman** [comment]
@trevilo that look reasonable?

**Comment by vikramvgarg** [comment]
Can you also do a line plot of nu ?

On Wed, Apr 1, 2015 at 4:47 PM, Paul T. Bauman <notifications@github.com>
wrote:

> @trevilo <https://github.com/trevilo> that look reasonable?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/grinsfem/grins/pull/186#issuecomment-88641638>.
>



-- 
Vikram Garg
Postdoctoral Associate
Predictive Engineering and Computational Science (PECOS)
The University of Texas at Austin
http://web.mit.edu/vikramvg/www/

http://vikramvgarg.wordpress.com/
http://www.runforindia.org/runners/vikramg

**Comment by pbauman** [comment]
sa_nu

**Comment by vikramvgarg** [comment]
Yup, that looks right.

On Wed, Apr 1, 2015 at 4:51 PM, Paul T. Bauman <notifications@github.com>
wrote:

> [image: sa_nu]
> <https://cloud.githubusercontent.com/assets/3051555/6953509/c1ff4e58-d897-11e4-873a-775810499435.png>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/grinsfem/grins/pull/186#issuecomment-88643383>.
>



-- 
Vikram Garg
Postdoctoral Associate
Predictive Engineering and Computational Science (PECOS)
The University of Texas at Austin
http://web.mit.edu/vikramvg/www/

http://vikramvgarg.wordpress.com/
http://www.runforindia.org/runners/vikramg

**Comment by trevilo** [comment]
Yeah, I agree.  Looks reasonable.

**Comment by pbauman** [comment]
Cool, thanks. I'm closing this out. Will open a new PR once I'm done polishing this later tonight.

**Pull request closed without merging**
