### PR TITLE
More shadow fixes

### PR DESCRIPTION
**Pull request by pbauman**
Founds these as part of the work in `input-materials-redo` branch. I'd like to merge this ASAP, and I've tested, but I'd still feel better if @nicholasmalaya hit this. @nicholasmalaya are you using these Physics? If so, could you run a case make sure this doesn't change anything for you?

### CODE REVIEW

**Comment by pbauman** [comment]
*ping* @nicholasmalaya

**Comment by roystgnr** [comment]
Yikes!

This looks like an obvious atavism fix, and I can't come up with any way it would have led to a bug, though.  If we're not tripping the penalty poiseuille case then I think we should be safe to merge without double-checking old results.

**Comment by nicholasmalaya** [comment]
I've been planning on looking at this but I won't be getting to it today. I'm actually not using these physics in production yet, but I could do some weaker tests. However, if it is not tripping @roystgnr regression for the fan, I think this should be good to go.

**Comment by roystgnr** [comment]
You are using VelocityPenaltyAdjointStabilization in production, aren't you?

**Comment by roystgnr** [comment]
I'm afraid all my fan + turbine regression tests are unstabilized.

**Comment by nicholasmalaya** [comment]
> You are using VelocityPenaltyAdjointStabilization in production, aren't you?

Absolutely, however, when I looked at the changes I only saw edits to velocity_drag, not the velocity penalty proper. Is the drag function automatically being applied to that? I thought not.

**Comment by roystgnr** [comment]
Ha!  I misread; you're correct.

**Comment by roystgnr** [comment]
If we don't have *any* production runs with questionable code to double-check, then let's just merge the less-questionable code now.

**Pull request merged**
