### PR TITLE
Use LIBMESH_CXXFLAGS during libMesh config testing

### PR DESCRIPTION
**Pull request by pbauman**
Before we weren't setting CXXFLAGS for the libMesh tests and it's
possible this led to some weirdness during the configuration tests,
particularly with the OpenMP flags.

@nicholasmalaya please confirm this fixes your configure issue on LS5.

### CODE REVIEW

**Comment by nicholasmalaya** [comment]
Sadly I'm getting the same error!
My configure line looks like:
<pre>
../configure --prefix=$pref/$nm LIBMESH_DIR=$pref/2016-3-2-libmesh BOOST_DIR=$TACC_BOOST_DIR CC=gcc MPICC=mpicc CXX=g++ MPICXX=mpicxx METHODS='dbg devel prof oprof opt'
</pre>

I am attaching the config.log, in case I'm giving misleading information, but still appears to be an omp related issue.
[config.log.txt](https://github.com/grinsfem/grins/files/178568/config.log.txt)

**Comment by nicholasmalaya** [comment]
Also fyi this is my module env:

<pre>
login1.ls5(53)$ module list

Currently Loaded Modules:
  1) intel/16.0.1   2) cray_mpich/7.3.0   3) TACC/1.0   4) autotools/1.1   5) git/2.6.4   6) boost/1.59   7) petsc/3.6
</pre>

**Comment by pbauman** [comment]
As an aside:

> METHODS='dbg devel prof oprof opt'

This almost certainly doesn't behave like you expect it to. GRINS currently only supports one `METHOD` at a time. So, probably, `METHODS` is ignored and you're getting `opt` by default.

**Comment by nicholasmalaya** [comment]
hmm, good to know, thanks

**Comment by pbauman** [comment]
Did you bootstrap after pulling this? You'd have to bootstrap. I don't see any of the `CXXFLAGS` that should be there in the compile line in your config.txt.

**Comment by nicholasmalaya** [comment]
I did, but after it failed I did one better and deleted the entire repo and did a fresh pull. Same error.

**Comment by pbauman** [comment]
> This almost certainly doesn't behave like you expect it to. GRINS currently only supports one METHOD at a time. So, probably, METHODS is ignored and you're getting opt by default.

And I can see how you'd be confused. I think the libMesh description got updated for the "plural" case after I wrote the GRINS bit. I'll update the front documentation to be more specific.

**Comment by nicholasmalaya** [comment]
I'm an idiot, this is a branch. I'm pulling from master. Sorry for being daft.

**Comment by nicholasmalaya** [comment]
Ok it is building at least...

**Comment by pbauman** [comment]
Great! This is probably good to merge, then, but I'll leave this open in case you run into other, similar troubles.

**Comment by nicholasmalaya** [comment]
Sigh, sorry the reply was so slow. I think that this ticket is fixed, in that we are getting a different error :p 

It looks as if the CXXFLAGS are being set correctly, 
<pre>
LIBMESH_CXXFLAGS='-std=gnu++11 -O3 -unroll -w0 -ftz -fopenmp'
</pre>

but here is my error: 

<pre>
login2.ls5(138)$ make
make  all-recursive
make[1]: Entering directory `/work/00000/npm7/lonestar/paul_grins/build'
Making all in src
make[2]: Entering directory `/work/00000/npm7/lonestar/paul_grins/build/src'
  CXXLD    libgrins.la
/opt/apps/gcc/4.9.3/lib/gcc/x86_64-unknown-linux-gnu/4.9.3/../../../../x86_64-unknown-linux-gnu/bin/ld: cannot find -lmpichf90_intel
collect2: error: ld returned 1 exit status
make[2]: *** [libgrins.la] Error 1
make[2]: Leaving directory `/work/00000/npm7/lonestar/paul_grins/build/src'
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory `/work/00000/npm7/lonestar/paul_grins/build'
make: *** [all] Error 2
</pre>

So now its not pulling in the right mpichf90_intel. Scanning the config.log (which is attached) I'm surprised that it even needs this... is it a BLAS dependency?

**Comment by nicholasmalaya** [comment]
Ooops, actually attaching config.log to this ticket this time. 
[config.log.txt](https://github.com/grinsfem/grins/files/182835/config.log.txt)

I rename it config.log.txt because github is too stupid to realize its just ascii text and blocks .log attachments.

**Comment by pbauman** [comment]
Can you post the output of `make V=1` for the linking step? How did you build libMesh? i.e. did you use CXX=mpicxx, etc? But I don't know how the Fortran crap is entering. Probably that came from PETSc, but I have no clue what that should matter here.

**Comment by pbauman** [comment]
I wonder if maybe your MPI module there doesn't have the path setup right for the libraries? Maybe the Intel install is FUBAR'ed?

**Comment by pbauman** [comment]
OK. Just for giggles, try this: Add `FC=mpif90` to your configure line. I have no idea why that should matter, but just for symmetry with `CC`, `CXX` on your configure line. But there's not a single line of Fortran in GRINS, so I'm not sure where's it picking that up from.

May checkout the `libgrins.la` file and see that library shows up in the dependency list somewhere?

**Comment by nicholasmalaya** [comment]
adding FC=mpif90 to my libmesh configure line,
<pre>
../configure --prefix=$pref/$nm BOOST_DIR=$TACC_BOOST_DIR METHODS='dbg devel prof oprof opt' CC=gcc MPICC=mpicc CXX=g++ MPICXX=mpicxx FC=mpif90 --enable-everything --enable-parmesh --disable-trilinos 
</pre>

*appears* to have fixed things. I now have a completed GRINS build on LS5. I'm running tests to ensure nothing has changed, will update ASAP and we can discuss closing this ticket out. I think we are cooking with CH4!

**Comment by nicholasmalaya** [comment]
I'm getting every indication this is functioning correctly. I'm not detecting any reason to delay merging. :+1:

**Comment by nicholasmalaya** [comment]
A curiosity (see attached for more detail)
[libgrins.la.txt](https://github.com/grinsfem/grins/files/182950/libgrins.la.txt)

: 

<pre>
# Libraries that this one depends upon.                                                                                                                                                                                                       
dependency_libs=' /work/00000/npm7/lonestar/LIBRARIES/2016-3-21-libmesh/lib/libmesh_opt.la -lcilkrts -L/opt/apps/intel16/cray_mpich_7_3/petsc/3.6/haswell/lib -L/opt/cray/xpmem/default/lib64 -L/opt/cray/ugni/default/lib64 -L/opt/cray/udre\
g/default/lib64 -L/opt/cray/pmi/default/lib64 -L/opt/cray/dmapp/default/lib64 -L/opt/cray/mpt/default/gni/mpich-intel/14.0/lib -L/opt/apps/gcc/4.9.3/lib64 -L/opt/apps/gcc/4.9.3/x86_64-unknown-linux-gnu/lib -L/opt/apps/gcc/4.9.3/lib -L/op\
t/apps/intel16/cray_mpich_7_2/phdf5/1.8.16/x86_64/lib /opt/apps/gcc/4.9.3/lib/../lib64/libcilkrts.la /work/00000/npm7/lonestar/LIBRARIES/2016-3-21-libmesh/lib/libnetcdf.la -lcurl -lpetsc -lcmumps -ldmumps -lsmumps -lzmumps -lmumps_common\
 -lpord -lscalapack -lHYPRE -lspai -lml -lmkl_intel_lp64 -lmkl_sequential -lmkl_core -lparmetis -lmetis /opt/apps/intel16/cray_mpich_7_2/phdf5/1.8.16/x86_64/lib/libhdf5hl_fortran.la /opt/apps/intel16/cray_mpich_7_2/phdf5/1.8.16/x86_64/li\
b/libhdf5_fortran.la /opt/apps/intel16/cray_mpich_7_2/phdf5/1.8.16/x86_64/lib/libhdf5_hl.la /opt/apps/intel16/cray_mpich_7_2/phdf5/1.8.16/x86_64/lib/libhdf5.la /opt/apps/intel16/cray_mpich_7_2/phdf5/1.8.16/x86_64/lib/libsz.la -lz -lssl -\
lcrypto -lchaco -lhwloc -lmpichf90_intel -lifport -lifcore_pic -lmpichcxx_intel -lmpich_intel -lrt -lugni -lpmi -lxpmem -ludreg -limf -lsvml -lirng -lipgo -ldecimal /opt/apps/gcc/4.9.3/lib/../lib64/libcilkrts.la -lpthread -lirc -lirc_s -\
ldl /opt/apps/gcc/4.9.3/lib/../lib64/libstdc++.la /opt/apps/gcc/4.9.3/lib/../lib64/libstdc++.la'   
</pre>

This is from libgrins.la -- so it looks as if is pulling parallel hdf5 support in from somewhere, which then includes Fortran90 support. Same thing is happening with the libmesh_opt.la I inspected. The full path is, 

<pre>
/opt/apps/intel16/cray_mpich_7_2/phdf5/1.8.16/x86_64/lib/libsz.la -lz -lssl -lcrypto -lchaco -lhwloc -lmpichf90_intel -lifport -lifcore_pic -lmpichcxx_\
intel -lmpich_intel -lrt -lugni -lpmi -lxpmem -ludreg -limf -lsvml -lirng -lipgo -ldecimal
</pre> 

Which strongly implies to me that the cray Intel16 module is borked somehow. To give further evidence, 

<pre>
login2.ls5(218)$ module list

Currently Loaded Modules:
  1) intel/16.0.1   2) cray_mpich/7.3.0   3) TACC/1.0   4) autotools/1.1   5) git/2.6.4   6) boost/1.59   7) petsc/3.6
</pre>

Is my module env. So I don't (explicitly) call for HDF!

**Comment by pbauman** [comment]
That very well may be PETSc. I think I saw some traffic on petsc-dev the other day about them using parallel HDF5. But that's just speculation. Glad you're up and running.

**Pull request merged**
