### PR TITLE
Make check fixes

### PR DESCRIPTION
**Pull request by roystgnr**
I think there may be more subtle bugs that I can kick up with different settings, but this along with https://github.com/libMesh/libmesh/pull/868 should be at least enough to get one "make check" working for me.

### CODE REVIEW

**Comment by roystgnr** [comment]
Wait, this isn't complete yet.

**Comment by roystgnr** [comment]
I cranked down solver tolerances, but didn't replace the gold standard files with files generated at those tolerances.  I'll get to that step late tonight.

**Comment by roystgnr** [comment]
That was sufficient to fix these tests for me.  I'm still looking into what seems to be an unrelated regression, and I'll do the "LIBMESH_RUN='mpirun -np $num'" from 1 to 20 one of these days to make sure the new tests' solver options are solid.

**Comment by pbauman** [comment]
[test.txt](https://github.com/grinsfem/grins/files/176379/test.txt)

That patch file gets make check passing for me with `LIBMESH_RUN=mpiexec -np 8`

**Comment by pbauman** [comment]
Err, that's with GRINS at 94e8b17 and the tip of libMesh master (as of about an hour ago).

**Comment by pbauman** [comment]
I just about have a patch for the `-np 16` case. I had to change `dirichlet_nan.sh` options to get it work. Will test with -np 12 to make sure my version works there too. Will post patch once this `make check` pass is done running.

**Comment by pbauman** [comment]
[test2.txt](https://github.com/grinsfem/grins/files/176496/test2.txt)

This patch, diff'ed from befa025, gets me going with `mpiexec -np 16`. I tried the `dirichlet_nan.sh` changes with `-np 12` and it worked for me.

**Comment by pbauman** [comment]
Figures that `-np 14` would somehow be weird. In addition to the test2.txt patch, here's a patch for the `locally_refine.sh` test that broke with `-np 14`:

<pre>
diff --git a/test/input_files/locally_refine.in b/test/input_files/locally_refine.in
index 054f3d5..9f2b438 100644
--- a/test/input_files/locally_refine.in
+++ b/test/input_files/locally_refine.in
@@ -63,7 +63,7 @@ tau_factor = '0.05'
 
 #Linear and nonlinear solver options
 [linear-nonlinear-solver]
-max_nonlinear_iterations =  25
+max_nonlinear_iterations =  50
 max_linear_iterations = 2500
 
 verify_analytic_jacobians = 0.0
diff --git a/test/regression/locally_refine.sh b/test/regression/locally_refine.sh
index df2f4e9..0082710 100755
--- a/test/regression/locally_refine.sh
+++ b/test/regression/locally_refine.sh
@@ -4,6 +4,6 @@ PROG="${GRINS_TEST_DIR}/grins_flow_regression"
 
 INPUT="${GRINS_TEST_INPUT_DIR}/locally_refine.in ${GRINS_TEST_DATA_DIR}/locally_refine.xdr 1.0e-8"
 
-PETSC_OPTIONS="-pc_type asm -pc_asm_overlap 2 -sub_pc_factor_levels 4"
+PETSC_OPTIONS="-pc_type asm -pc_asm_overlap 2 -sub_pc_factor_shift_type nonzero -sub_pc_factor_levels 4"
 
 ${LIBMESH_RUN:-} $PROG $INPUT $PETSC_OPTIONS
</pre>

Running with `-np 15` now.

**Comment by pbauman** [comment]
`LIBMESH_RUN="mpiexec -np 15"` works for me with the above patches.

Trying `-np 16` again for giggles.

**Comment by pbauman** [comment]
Gawd. Apparently the Stokes tests sometimes would fail at `-np 16`. The below patch updates the `exact_soln/stokes*` tests with a better preconditioner. This is in addition to the above patches.

<pre>
diff --git a/test/exact_soln/stokes_poiseuille_flow.sh b/test/exact_soln/stokes_poiseuille_flow.sh
index 8284aae..644a474 100755
--- a/test/exact_soln/stokes_poiseuille_flow.sh
+++ b/test/exact_soln/stokes_poiseuille_flow.sh
@@ -5,8 +5,10 @@ set -e
 INPUT="${GRINS_TEST_INPUT_DIR}/stokes_poiseuille_flow_input.in"
 TESTDATA="./stokes_poiseuille_flow.xdr"
 
+PETSC_OPTIONS="-pc_type asm -pc_asm_overlap 2 -sub_pc_factor_shift_type nonzero -sub_pc_factor_levels 4"
+
 # First run the case with grins
-${LIBMESH_RUN:-} ${GRINS_BUILDSRC_DIR}/grins $INPUT
+${LIBMESH_RUN:-} ${GRINS_BUILDSRC_DIR}/grins $INPUT $PETSC_OPTIONS
 
 # Now run the test part to make sure we're getting the correct thing
 ${LIBMESH_RUN:-} ${GRINS_TEST_DIR}/generic_exact_solution_testing_app \
diff --git a/test/exact_soln/stokes_poiseuille_flow_parsed_viscosity.sh b/test/exact_soln/stokes_poiseuille_flow_parsed_viscosity.sh
index a9a37d7..aa87197 100755
--- a/test/exact_soln/stokes_poiseuille_flow_parsed_viscosity.sh
+++ b/test/exact_soln/stokes_poiseuille_flow_parsed_viscosity.sh
@@ -4,9 +4,10 @@ set -e
 
 INPUT="${GRINS_TEST_INPUT_DIR}/stokes_poiseuille_flow_parsed_viscosity_input.in"
 TESTDATA="./stokes_poiseuille_flow_parsed_viscosity.xdr"
+PETSC_OPTIONS="-pc_type asm -pc_asm_overlap 2 -sub_pc_factor_shift_type nonzero -sub_pc_factor_levels 4"
 
 # First run the case with grins
-${LIBMESH_RUN:-} ${GRINS_BUILDSRC_DIR}/grins $INPUT
+${LIBMESH_RUN:-} ${GRINS_BUILDSRC_DIR}/grins $INPUT $PETSC_OPTIONS
 
 # Now run the test part to make sure we're getting the correct thing
 ${LIBMESH_RUN:-} ${GRINS_TEST_DIR}/generic_exact_solution_testing_app \
diff --git a/test/exact_soln/stokes_poiseuille_flow_parsed_viscosity_parsed_conductivity.sh b/test/exact_soln/stokes_poiseuille_flow_parsed_viscosity_parsed_conductivity.sh
index 8461f31..50a5438 100755
--- a/test/exact_soln/stokes_poiseuille_flow_parsed_viscosity_parsed_conductivity.sh
+++ b/test/exact_soln/stokes_poiseuille_flow_parsed_viscosity_parsed_conductivity.sh
@@ -4,9 +4,10 @@ set -e
 
 INPUT="${GRINS_TEST_INPUT_DIR}/stokes_poiseuille_flow_parsed_viscosity_parsed_conductivity_input.in"
 TESTDATA="./stokes_poiseuille_flow_parsed_viscosity_parsed_conductivity.xdr"
+PETSC_OPTIONS="-pc_type asm -pc_asm_overlap 2 -sub_pc_factor_shift_type nonzero -sub_pc_factor_levels 4"
 
 # First run the case with grins
-${LIBMESH_RUN:-} ${GRINS_BUILDSRC_DIR}/grins $INPUT
+${LIBMESH_RUN:-} ${GRINS_BUILDSRC_DIR}/grins $INPUT $PETSC_OPTIONS
 
 # Now run the test part to make sure we're getting the correct thing
 ${LIBMESH_RUN:-} ${GRINS_TEST_DIR}/generic_exact_solution_testing_app \
</pre>

**Comment by pbauman** [comment]
OK, `regression/low_mach_cavity_benchmark.sh` failed at `-np 13`. Looks like we just needed to tighten up the relative tolerance on the PETSc linear solve. Here's a patch for that. Note I did a bash for loop from 1 to 16 processors and this test passed all (I have *not* done that for all the previous tests, just this one).

<pre>
diff --git a/test/regression/low_mach_cavity_benchmark.sh b/test/regression/low_mach_cavity_benchmark.sh
index 6a048d0..4b6eda4 100755
--- a/test/regression/low_mach_cavity_benchmark.sh
+++ b/test/regression/low_mach_cavity_benchmark.sh
@@ -5,6 +5,6 @@ PROG="${GRINS_TEST_DIR}/low_mach_cavity_benchmark_regression"
 INPUT="${GRINS_TEST_INPUT_DIR}/low_mach_cavity_benchmark_regression_input.in"
 
 # A MOAB preconditioner
-PETSC_OPTIONS="-pc_type asm -pc_asm_overlap 8 -sub_pc_type ilu -sub_pc_factor_mat_ordering_type 1wd -sub_pc_factor_levels 10"
+PETSC_OPTIONS="-pc_type asm -pc_asm_overlap 8 -sub_pc_type ilu -sub_pc_factor_shift_type nonzero -sub_pc_factor_mat_ordering_type 1wd -sub_pc_factor_levels 10 -ksp_rtol 1.0e-8"
 
 ${LIBMESH_RUN:-} $PROG $INPUT $PETSC_OPTIONS
</pre>

**Comment by pbauman** [comment]
Running 

`maxnp=16; for i in $(seq $maxnp); do export LIBMESH_RUN="mpiexec -np $i"; j=$(($maxnp/$i)); echo LIBMESH_RUN is $LIBMESH_RUN; make -j $j check; done`

with all the above patches. Will report on results.

**Comment by roystgnr** [comment]
Doing the same up to 20 (although all I need is 12, good to leave room for expansion) on ParallelMesh.

**Comment by pbauman** [comment]
Here's my results (everything passed on np = 1,2,3) up to, but not including, `-np 13`. In theory everything 13+ should pass. I started this without any of @roystgnr's fixes, just mine, so hopefully some of these will go away.

<pre>
LIBMESH_RUN is mpiexec -np 4
FAIL: regression/penalty_poiseuille_stab.sh
FAIL: regression/locally_refine.sh
# FAIL:  2
LIBMESH_RUN is mpiexec -np 5
FAIL: regression/reacting_low_mach_antioch_kinetics_theory.sh
# FAIL:  1
LIBMESH_RUN is mpiexec -np 6
FAIL: regression/reacting_low_mach_antioch_statmech_blottner_eucken_lewis_constant_catalytic_wall.sh
# FAIL:  1
LIBMESH_RUN is mpiexec -np 7
# FAIL:  0
LIBMESH_RUN is mpiexec -np 8
# FAIL:  0
LIBMESH_RUN is mpiexec -np 9
FAIL: exact_soln/stokes_poiseuille_flow.sh
# FAIL:  1
LIBMESH_RUN is mpiexec -np 10
# FAIL:  0
LIBMESH_RUN is mpiexec -np 11
FAIL: regression/locally_refine.sh
# FAIL:  1
LIBMESH_RUN is mpiexec -np 12
FAIL: regression/penalty_poiseuille.sh
FAIL: regression/reacting_low_mach_antioch_kinetics_theory.sh
# FAIL:  2
</pre>

**Comment by pbauman** [comment]
OK, here's the final tally (`locally_refine.sh` is making a liar out of me). I'll fetch the last set of changes, focus on these failures, and then run the whole shebang again. Note the exact command I ended up using was

`maxnp=16; for i in $(seq 4 $maxnp); do export LIBMESH_RUN="mpiexec -np $i"; j=$(($maxnp/$i)); echo LIBMESH_RUN is $LIBMESH_RUN | tee -a check.log; make -j $j check 2>&1 | tee -a check.log; done`

so that I could easily grep the output:

`grep -e LIBMESH_RUN -e FAIL check.log | grep -v XFAIL`

(After this gets sorted, I'll make a PR that has the command above for running these tests with a script to help facilitate running these kind of tests and helping ensure that @roystgnr doesn't fly up to Buffalo and cut my fingers off.)

<pre>
LIBMESH_RUN is mpiexec -np 4
FAIL: regression/penalty_poiseuille_stab.sh
FAIL: regression/locally_refine.sh
# FAIL:  2
LIBMESH_RUN is mpiexec -np 5
FAIL: regression/reacting_low_mach_antioch_kinetics_theory.sh
# FAIL:  1
LIBMESH_RUN is mpiexec -np 6
FAIL: regression/reacting_low_mach_antioch_statmech_blottner_eucken_lewis_constant_catalytic_wall.sh
# FAIL:  1
LIBMESH_RUN is mpiexec -np 7
# FAIL:  0
LIBMESH_RUN is mpiexec -np 8
# FAIL:  0
LIBMESH_RUN is mpiexec -np 9
FAIL: exact_soln/stokes_poiseuille_flow.sh
# FAIL:  1
LIBMESH_RUN is mpiexec -np 10
# FAIL:  0
LIBMESH_RUN is mpiexec -np 11
FAIL: regression/locally_refine.sh
# FAIL:  1
LIBMESH_RUN is mpiexec -np 12
FAIL: regression/penalty_poiseuille.sh
FAIL: regression/reacting_low_mach_antioch_kinetics_theory.sh
# FAIL:  2
LIBMESH_RUN is mpiexec -np 13
# FAIL:  0
LIBMESH_RUN is mpiexec -np 14
FAIL: regression/locally_refine.sh
# FAIL:  1
LIBMESH_RUN is mpiexec -np 15
# FAIL:  0
LIBMESH_RUN is mpiexec -np 16
# FAIL:  0
</pre>

**Comment by roystgnr** [comment]
I'm good from 12 to 18 processes now.  Rerunning on 1 to 11 to make sure nothing there regressed.

Looking forward to your "script to test every processor count" PR.  Perhaps we could also:

1) Allow input file variables to be overridden on the command line, a la the new adaptivity_ex3 in libMesh

2) Run tests with Mesh/class=parallel and Mesh/class=serial regardless of what the default is?

**Comment by pbauman** [comment]
[test_final.txt](https://github.com/grinsfem/grins/files/176889/test_final.txt)


The attached patch file (diff'ed from bba57be) gets rid of all my failures from the previous set. I'm rerunning everything again to make sure I didn't miss anything. Will post here once that's done (hourish).

Note the  `regression/penalty_poiseuille_stab.sh` case was pretty finicky for me, which is why I upped the tolerance. I made a note in there that once I migrate the regression tests to something similar to the `exact_soln` tests, we can set per-variable tolerances. The others were either the `shift_type` default switch or tighter solver tolerances.

> Looking forward to your "script to test every processor count" PR.

I'll try and drop that in tonight.

> Allow input file variables to be overridden on the command line, a la the new adaptivity_ex3 in libMesh

This thought had occurred to me at some point, but wasn't sure how to do it in an automated way (i.e. without touching every single input variable). Will check out the example.

>  Run tests with Mesh/class=parallel and Mesh/class=serial regardless of what the default is?

If we can do the run-time-input-variable-override, then this should be easy, right? I guess only if the input file has it in there? Need to look at that libMesh example. Regardless, my thinking was that once I can get a CI server setup (if the hardware hasn't been ordered it should be by the end of the week), then there can be `SerialMesh`-default and `ParallelMesh`-default libMesh install trees (with the appropriate `METHOD`s) and then the test suite gets run against all of those. Of course is up for discussion. I do agree we need a more automated way of hitting both `SerialMesh` and `ParallelMesh`

**Comment by roystgnr** [comment]
Hopefully that should be the final tweaking.  I'll let you know tonight if we're still good from 1-18 procs.

**Comment by pbauman** [comment]
My test completed through 16 processes and all went well, no test failures. This is good to merge when you're ready.

**Comment by roystgnr** [comment]
Works up to 18 procs for me now.

**Pull request merged**
