### PR TITLE
Bugfix for RayfireMesh refinement

### PR DESCRIPTION
**Pull request by tradowsk**
Upon refinement of rayfire elements, if the rayfire enters a parent element very near the boundary between 2 children, the starting child is not properly calculated.

A CPPUnit test was added to verify that the issue is resolved.

### CODE REVIEW

**Comment by pbauman** [comment]
Could you elaborate a bit more on the failure mode?

Also, I noticed [here](https://github.com/grinsfem/grins/pull/438/files#diff-e65e60adfe3e738c523f0053bb2a8f2fR402) that you initialize with a potentially bad value (I think that's an unsigned type). Use the corresponding `invalid_id` - grep through GRINS and/or libMesh for the right invalid_type.

**Comment by tradowsk** [comment]
Squashed in use of `invalid_uint` for the initialization value.

As for the original issue, sorry for the short explanation.

When refining rayfire elements, I start with the main mesh element that was just refined. I need to figure out through which child of that main mesh element the rayfire enters. However, should that entry point or `start_point` be a vertex between 2 children, then 

`main_elem->child(i)->contains_point(start_point)` 

would not always yield a valid starting child element, since that point is contained by 2 children. So what I did originally was check if the child elem contained the point, and if so, I walked a small distance along the rayfire and checked if that point was also inside the child elem. This works great when the start_point is in the middle of the element, or on a vertex. However, when the `start_point` is very near to the vertex, but not quite on it, then my small walk along the rayfire would take me into the next child elem, and thus I was getting results where none of the children contained the `start_point` which resulted in a `segfault`.

With this fix, if a child elem contains the `start_point`, I first check if `start_point` is a vertex of the child elem. If it is, I can do my small walk to see if I am in the right child elem. If `start_point` is not a vertex, then it can only be contained by one child elem, so there is no need to do that small walk that was causing my issues.

The CPPUnit test added starts the rayfire very close to a postrefinement vertex, and after refinement, checks to make sure the right elems are included in the rayfire.

**Comment by pbauman** [comment]
OK, thanks for the more detailed explanation.

**Comment by pbauman** [comment]
I would add a `libmesh_assert_not_equal_to(start_child,libMesh::invalid_uint)` at the end of your child loop (looks like line 436 of rayfire_mesh.C) in case the logic every changes.

**Comment by tradowsk** [comment]
Squashed in the `assert`

**Comment by pbauman** [comment]
`make check` still passing? (Grumbles about Civet being open-sourced.)

**Comment by tradowsk** [comment]
Yes, both for the rayfire tests and the IntegratedFunction test that originally brought up this issue

**Pull request merged**
