### PR TITLE
Guard against get_elem() calls for SCALAR variables

### PR DESCRIPTION
**Pull request by pbauman**
Basically in conjunction with libMesh/libmesh#467. With that plus this PR, master `make check` runs cleanly.

### CODE REVIEW

**Comment by roystgnr** [comment]
Wouldn't adding a has_elem() check to _general_residual be better than forking it into _nonlocal_residual?

**Comment by pbauman** [comment]
Fair enough. I was 6-in-one/half-dozen-the-other about it, but you're probably right. Updated accordingly. `make check` passing.

**Comment by roystgnr** [comment]
Looks good to me; thanks.

**Comment by pbauman** [comment]
Cool, thanks. I'll merge this after the libMesh PR.

**Pull request merged**
