### PR TITLE
Adjoint plotting

### PR DESCRIPTION
**Pull request by pbauman**
Added functions to output adjoint solutions. Have only tested the steady case using the cavity benchmark example. Seems to be doing the right thing.

### CODE REVIEW

**Comment by pbauman** [comment]
Probably collides with #271. Go ahead and merge that and I"ll rebase.

**Comment by roystgnr** [comment]
:+1:

**Comment by roystgnr** [comment]
We should add a call to this from the GRINS adjoint_qoi_parameter_sensitivity methods.

**Comment by pbauman** [comment]
Good, suggestion, I'll do that.

**Comment by pbauman** [comment]
Rebased.

**Comment by pbauman** [comment]
I'll go ahead and merge this now. The adjoint solve and management of when to output the adjoint needs an overhaul, which I'll do right now in another PR. At least can get this in if folks want to do some dirty hacks in the mean time.

**Pull request merged**
